	const_def

	const DENJUU_HP
	const DENJUU_SPEED
	const DENJUU_ATTACK
	const DENJUU_DEFENSE
	const DENJUU_SPATK
	const DENJUU_SPDEF
	const DENJUU_MOVE1
	const DENJUU_MOVE2
	const DENJUU_MOVE3
	const DENJUU_MOVE4
	const DENJUU_BASE_YIELD
	const DENJUU_EVO_LEVEL
	const DENJUU_EVO_SPECIES
	const DENJUU_TYPE
	const DENJUU_MOVE3_LEVEL
	const DENJUU_MOVE4_LEVEL

MAX_LEVEL EQU 100
