	const_def

	const TSUNONASU
	const KOCHIA
	const OSHE
	const KESHI
	const CRYPTO
	const MONSTERA
	const FUNGUS
	const HIOUGI
	const PUNICA
	const GUMI
	const SUGURI
	const GANRAIKOU
	const BYAKUBU
	const TELOPEA
	const MANTEA
	const IXORA
	const MYRTUS
	const LYCHNIS
	const LAPEIROUSIA
	const BUBARIA
	const ANGIOS
	const GYMNOS
	const LIRIOPE
	const WARATAH
	const SORGHUM
	const ERYNGO
	const NORIUTSUGI
	const PAMPAS
	const RHODANTHE
	const LICORICE
	const VIBURNUM
	const FUNNEL
	const VANDA
	const UIKYOU
	const OBANA
	const FIREKOKKO
	const RAYGOTEN
	const DRILARMOR
	const CHAMELAN
	const CRYPTOARM
	const SHELLSTERA
	const FUNGEIST
	const BALLTAMUS
	const BURENICA
	const GERON
	const BERZELIA
	const NIGELLA
	const MUSA
	const NETARO
	const NEJIRO
	const GODETIA
	const CURCUMA
	const TESSEN
	const HELIOPSIS
	const HAGUMANOKI
	const GILERTH
	const RAYGIRTH
	const ARMARU
	const CHAMERAID
	const CRYPTORIDE
	const WORMITERALA
	const FUNGBLADE
	const BULLTAMUS
	const PUNEEDLE
	const KERORIN
	const SUGULAI
	const CORTOS
	const GAIURUS
	const MIDOTOR
	const OCTOR
	const HITODEIGHT
	const GHOSBOAR
	const RASENMAI
	const SCORPIL
	const ARMCRAB
	const ANGIORN
	const GYMRACE
	const LIRIONPU
	const WHITAH
	const POTZAL
	const ARANEIDA
	const GADHORO
	const CLIOGERA
	const GUST
	const REIGE
	const TOGERUKA
	const RAIGALEON
	const GADORKUMA
	const ABIRAS
	const ALPHAGOS
	const KIYORUKA
	const GYMGARTH
	const BAIONPU
	const WARUTAH
	const GUNTZATL
	const ARAKUIDA
	const BADHORO
	const LAMPGERA
	const TEMPEST
	const ZUDOON
	const HIYU
	const GAMAZUMI
	const PAPAVER
	const GAMURU
	const BOUVARDI
	const GAULTHERIA
	const DIPSACUS
	const KAYA
	const DENFARE
	const ANGIEON
	const EASYDOG
	const TRICERARMOR
	const CRYPTOSNIPE
	const FUNGBOOST
	const VEENICA
	const SAIGULIGER
	const ARMEDURUS
	const OCTORIFLE
	const ERASERBOAR
	const SPEARNEEDLE
	const GILGIERTH
	const UNIARMOR
	const CRYPTOBURN
	const FUNGMACHINE
	const PUNISTO
	const SUGULINE
	const MACHURUS
	const OCTAGUN
	const MUMMYBOAR
	const KINGPIN
	const BEEBALM
	const SALAL
	const ENISHIDA
	const TULBAGHIA
	const KIRINGIKU
	const ANGILANCE
	const GYMGANON
	const SAIOPE
	const WATTAH
	const QUETZAKING
	const ARAKUDABARAN
	const PUNKHORO
	const VIKINGURIN
	const STORM
	const MUTOOM
	const GYPSOPHI
	const RUSCUS
	const MAORAN
	const ZEA
	const GONUM
	const ANGIPOWER
	const GYMZYRUS
	const CANONOPE
	const CALM
	const RYUUGUU
	const GIGAGIGERTH
	const BARRIARM
	const CRYPTOKNIGHT
	const FUNGWAR
	const BASHOU
	const ANGIGORGO
	const GYMBARON
	const LIRIMONARCH
	const ENTEIOH
	const GOLAKING
	const KANZOU
	const ORNITHOGALUM
	const GENTIANA
	const YARROW
	const ANGIOROS
	const GYMZATAN
	const DOOMSDAY
	const DENDEL
	const TELETEL
