	const_def

	const EVENT_000
	const EVENT_001
	const EVENT_002
	const EVENT_003
	const EVENT_004
	const EVENT_005
	const EVENT_006
	const EVENT_007
	const EVENT_008
	const EVENT_009
	const EVENT_00A
	const EVENT_00B
	const EVENT_00C
	const EVENT_00D
	const EVENT_00E
	const EVENT_00F
	const EVENT_010
	const EVENT_011
	const EVENT_012
	const EVENT_013
	const EVENT_014
	const EVENT_015
	const EVENT_016
	const EVENT_017
	const EVENT_018
	const EVENT_019
	const EVENT_01A
	const EVENT_01B
	const EVENT_01C
	const EVENT_01D
	const EVENT_01E
	const EVENT_01F
	const EVENT_020
	const EVENT_021
	const EVENT_022
	const EVENT_023
	const EVENT_024
	const EVENT_025
	const EVENT_026
	const EVENT_027
	const EVENT_028
	const EVENT_029
	const EVENT_02A
	const EVENT_02B
	const EVENT_02C
	const EVENT_02D
	const EVENT_02E
	const EVENT_02F
	const EVENT_030
	const EVENT_031
	const EVENT_032
	const EVENT_033
	const EVENT_034
	const EVENT_035
	const EVENT_036
	const EVENT_037
	const EVENT_038
	const EVENT_039
	const EVENT_03A
	const EVENT_03B
	const EVENT_03C
	const EVENT_03D
	const EVENT_03E
	const EVENT_03F
	const EVENT_040
	const EVENT_041
	const EVENT_042
	const EVENT_043
	const EVENT_044
	const EVENT_045
	const EVENT_046
	const EVENT_047
	const EVENT_048
	const EVENT_049
	const EVENT_04A
	const EVENT_04B
	const EVENT_04C
	const EVENT_04D
	const EVENT_04E
	const EVENT_04F
	const EVENT_050
	const EVENT_051
	const EVENT_052
	const EVENT_053
	const EVENT_054
	const EVENT_055
	const EVENT_056
	const EVENT_057
	const EVENT_058
	const EVENT_059
	const EVENT_05A
	const EVENT_05B
	const EVENT_05C
	const EVENT_05D
	const EVENT_05E
	const EVENT_05F
	const EVENT_060
	const EVENT_061
	const EVENT_062
	const EVENT_063
	const EVENT_064
	const EVENT_065
	const EVENT_066
	const EVENT_067
	const EVENT_068
	const EVENT_069
	const EVENT_06A
	const EVENT_06B
	const EVENT_06C
	const EVENT_06D
	const EVENT_06E
	const EVENT_06F
	const EVENT_070
	const EVENT_071
	const EVENT_072
	const EVENT_073
	const EVENT_074
	const EVENT_075
	const EVENT_076
	const EVENT_077
	const EVENT_078
	const EVENT_079
	const EVENT_07A
	const EVENT_07B
	const EVENT_07C
	const EVENT_07D
	const EVENT_07E
	const EVENT_07F
	const EVENT_080
	const EVENT_081
	const EVENT_082
	const EVENT_083
	const EVENT_084
	const EVENT_085
	const EVENT_086
	const EVENT_087
	const EVENT_088
	const EVENT_089
	const EVENT_08A
	const EVENT_08B
	const EVENT_08C
	const EVENT_08D
	const EVENT_08E
	const EVENT_08F
	const EVENT_090
	const EVENT_091
	const EVENT_092
	const EVENT_093
	const EVENT_094
	const EVENT_095
	const EVENT_096
	const EVENT_097
	const EVENT_098
	const EVENT_099
	const EVENT_09A
	const EVENT_09B
	const EVENT_09C
	const EVENT_09D
	const EVENT_09E
	const EVENT_09F
	const EVENT_0A0
	const EVENT_0A1
	const EVENT_0A2
	const EVENT_0A3
	const EVENT_0A4
	const EVENT_0A5
	const EVENT_0A6
	const EVENT_0A7
	const EVENT_0A8
	const EVENT_0A9
	const EVENT_0AA
	const EVENT_0AB
	const EVENT_0AC
	const EVENT_0AD
	const EVENT_0AE
	const EVENT_0AF
	const EVENT_0B0
	const EVENT_0B1
	const EVENT_0B2
	const EVENT_0B3
	const EVENT_0B4
	const EVENT_0B5
	const EVENT_0B6
	const EVENT_0B7
	const EVENT_0B8
	const EVENT_0B9
	const EVENT_0BA
	const EVENT_0BB
	const EVENT_0BC
	const EVENT_0BD
	const EVENT_0BE
	const EVENT_0BF
	const EVENT_0C0
	const EVENT_0C1
	const EVENT_0C2
	const EVENT_0C3
	const EVENT_0C4
	const EVENT_0C5
	const EVENT_0C6
	const EVENT_0C7
	const EVENT_0C8
	const EVENT_0C9
	const EVENT_0CA
	const EVENT_0CB
	const EVENT_0CC
	const EVENT_0CD
	const EVENT_0CE
	const EVENT_0CF
	const EVENT_0D0
	const EVENT_0D1
	const EVENT_0D2
	const EVENT_0D3
	const EVENT_0D4
	const EVENT_0D5
	const EVENT_0D6
	const EVENT_0D7
	const EVENT_0D8
	const EVENT_0D9
	const EVENT_0DA
	const EVENT_0DB
	const EVENT_0DC
	const EVENT_0DD
	const EVENT_0DE
	const EVENT_0DF
	const EVENT_0E0
	const EVENT_0E1
	const EVENT_0E2
	const EVENT_0E3
	const EVENT_0E4
	const EVENT_0E5
	const EVENT_0E6
	const EVENT_0E7
	const EVENT_0E8
	const EVENT_0E9
	const EVENT_0EA
	const EVENT_0EB
	const EVENT_0EC
	const EVENT_0ED
	const EVENT_0EE
	const EVENT_0EF
	const EVENT_0F0
	const EVENT_0F1
	const EVENT_0F2
	const EVENT_0F3
	const EVENT_0F4
	const EVENT_0F5
	const EVENT_0F6
	const EVENT_0F7
	const EVENT_0F8
	const EVENT_0F9
	const EVENT_0FA
	const EVENT_0FB
	const EVENT_0FC
	const EVENT_0FD
	const EVENT_0FE
	const EVENT_0FF
	const EVENT_100
	const EVENT_101
	const EVENT_102
	const EVENT_103
	const EVENT_104
	const EVENT_105
	const EVENT_106
	const EVENT_107
	const EVENT_108
	const EVENT_109
	const EVENT_10A
	const EVENT_10B
	const EVENT_10C
	const EVENT_10D
	const EVENT_10E
	const EVENT_10F
	const EVENT_110
	const EVENT_111
	const EVENT_112
	const EVENT_113
	const EVENT_114
	const EVENT_115
	const EVENT_116
	const EVENT_117
	const EVENT_118
	const EVENT_119
	const EVENT_11A
	const EVENT_11B
	const EVENT_11C
	const EVENT_11D
	const EVENT_11E
	const EVENT_11F
	const EVENT_120
	const EVENT_121
	const EVENT_122
	const EVENT_123
	const EVENT_124
	const EVENT_125
	const EVENT_126
	const EVENT_127
	const EVENT_128
	const EVENT_129
	const EVENT_12A
	const EVENT_12B
	const EVENT_12C
	const EVENT_12D
	const EVENT_12E
	const EVENT_12F
	const EVENT_130
	const EVENT_131
	const EVENT_132
	const EVENT_133
	const EVENT_134
	const EVENT_135
	const EVENT_136
	const EVENT_137
	const EVENT_138
	const EVENT_139
	const EVENT_13A
	const EVENT_13B
	const EVENT_13C
	const EVENT_13D
	const EVENT_13E
	const EVENT_13F
	const EVENT_140
	const EVENT_141
	const EVENT_142
	const EVENT_143
	const EVENT_144
	const EVENT_145
	const EVENT_146
	const EVENT_147
	const EVENT_148
	const EVENT_149
	const EVENT_14A
	const EVENT_14B
	const EVENT_14C
	const EVENT_14D
	const EVENT_14E
	const EVENT_14F
	const EVENT_150
	const EVENT_151
	const EVENT_152
	const EVENT_153
	const EVENT_154
	const EVENT_155
	const EVENT_156
	const EVENT_157
	const EVENT_158
	const EVENT_159
	const EVENT_15A
	const EVENT_15B
	const EVENT_15C
	const EVENT_15D
	const EVENT_15E
	const EVENT_15F
	const EVENT_160
	const EVENT_161
	const EVENT_162
	const EVENT_163
	const EVENT_164
	const EVENT_165
	const EVENT_166
	const EVENT_167
	const EVENT_168
	const EVENT_169
	const EVENT_16A
	const EVENT_16B
	const EVENT_16C
	const EVENT_16D
	const EVENT_16E
	const EVENT_16F
	const EVENT_170
	const EVENT_171
	const EVENT_172
	const EVENT_173
	const EVENT_174
	const EVENT_175
	const EVENT_176
	const EVENT_177
	const EVENT_178
	const EVENT_179
	const EVENT_17A
	const EVENT_17B
	const EVENT_17C
	const EVENT_17D
	const EVENT_17E
	const EVENT_17F
	const EVENT_180
	const EVENT_181
	const EVENT_182
	const EVENT_183
	const EVENT_184
	const EVENT_185
	const EVENT_186
	const EVENT_187
	const EVENT_188
	const EVENT_189
	const EVENT_18A
	const EVENT_18B
	const EVENT_18C
	const EVENT_18D
	const EVENT_18E
	const EVENT_18F
	const EVENT_190
	const EVENT_191
	const EVENT_192
	const EVENT_193
	const EVENT_194
	const EVENT_195
	const EVENT_196
	const EVENT_197
	const EVENT_198
	const EVENT_199
	const EVENT_19A
	const EVENT_19B
	const EVENT_19C
	const EVENT_19D
	const EVENT_19E
	const EVENT_19F
	const EVENT_1A0
	const EVENT_1A1
	const EVENT_1A2
	const EVENT_1A3
	const EVENT_1A4
	const EVENT_1A5
	const EVENT_1A6
	const EVENT_1A7
	const EVENT_1A8
	const EVENT_1A9
	const EVENT_1AA
	const EVENT_1AB
	const EVENT_1AC
	const EVENT_1AD
	const EVENT_1AE
	const EVENT_1AF
	const EVENT_1B0
	const EVENT_1B1
	const EVENT_1B2
	const EVENT_1B3
	const EVENT_1B4
	const EVENT_1B5
	const EVENT_1B6
	const EVENT_1B7
	const EVENT_1B8
	const EVENT_1B9
	const EVENT_1BA
	const EVENT_1BB
	const EVENT_1BC
	const EVENT_1BD
	const EVENT_1BE
	const EVENT_1BF
	const EVENT_1C0
	const EVENT_1C1
	const EVENT_1C2
	const EVENT_1C3
	const EVENT_1C4
	const EVENT_1C5
	const EVENT_1C6
	const EVENT_1C7
	const EVENT_1C8
	const EVENT_1C9
	const EVENT_1CA
	const EVENT_1CB
	const EVENT_1CC
	const EVENT_1CD
	const EVENT_1CE
	const EVENT_1CF
	const EVENT_1D0
	const EVENT_1D1
	const EVENT_1D2
	const EVENT_1D3
	const EVENT_1D4
	const EVENT_1D5
	const EVENT_1D6
	const EVENT_1D7
	const EVENT_1D8
	const EVENT_1D9
	const EVENT_1DA
	const EVENT_1DB
	const EVENT_1DC
	const EVENT_1DD
	const EVENT_1DE
	const EVENT_1DF
	const EVENT_1E0
	const EVENT_1E1
	const EVENT_1E2
	const EVENT_1E3
	const EVENT_1E4
	const EVENT_1E5
	const EVENT_1E6
	const EVENT_1E7
	const EVENT_1E8
	const EVENT_1E9
	const EVENT_1EA
	const EVENT_1EB
	const EVENT_1EC
	const EVENT_1ED
	const EVENT_1EE
	const EVENT_1EF
	const EVENT_1F0
	const EVENT_1F1
	const EVENT_1F2
	const EVENT_1F3
	const EVENT_1F4
	const EVENT_1F5
	const EVENT_1F6
	const EVENT_1F7
	const EVENT_1F8
	const EVENT_1F9
	const EVENT_1FA
	const EVENT_1FB
	const EVENT_1FC
	const EVENT_1FD
	const EVENT_1FE
	const EVENT_1FF
	const EVENT_200
	const EVENT_201
	const EVENT_202
	const EVENT_203
	const EVENT_204
	const EVENT_205
	const EVENT_206
	const EVENT_207
	const EVENT_208
	const EVENT_209
	const EVENT_20A
	const EVENT_20B
	const EVENT_20C
	const EVENT_20D
	const EVENT_20E
	const EVENT_20F
	const EVENT_210
	const EVENT_211
	const EVENT_212
	const EVENT_213
	const EVENT_214
	const EVENT_215
	const EVENT_216
	const EVENT_217
	const EVENT_218
	const EVENT_219
	const EVENT_21A
	const EVENT_21B
	const EVENT_21C
	const EVENT_21D
	const EVENT_21E
	const EVENT_21F
	const EVENT_220
	const EVENT_221
	const EVENT_222
	const EVENT_223
	const EVENT_224
	const EVENT_225
	const EVENT_226
	const EVENT_227
	const EVENT_228
	const EVENT_229
	const EVENT_22A
	const EVENT_22B
	const EVENT_22C
	const EVENT_22D
	const EVENT_22E
	const EVENT_22F
	const EVENT_230
	const EVENT_231
	const EVENT_232
	const EVENT_233
	const EVENT_234
	const EVENT_235
	const EVENT_236
	const EVENT_237
	const EVENT_238
	const EVENT_239
	const EVENT_23A
	const EVENT_23B
	const EVENT_23C
	const EVENT_23D
	const EVENT_23E
	const EVENT_23F
	const EVENT_240
	const EVENT_241
	const EVENT_242
	const EVENT_243
	const EVENT_244
	const EVENT_245
	const EVENT_246
	const EVENT_247
	const EVENT_248
	const EVENT_249
	const EVENT_24A
	const EVENT_24B
	const EVENT_24C
	const EVENT_24D
	const EVENT_24E
	const EVENT_24F
	const EVENT_250
	const EVENT_251
	const EVENT_252
	const EVENT_253
	const EVENT_254
	const EVENT_255
	const EVENT_256
	const EVENT_257
	const EVENT_258
	const EVENT_259
	const EVENT_25A
	const EVENT_25B
	const EVENT_25C
	const EVENT_25D
	const EVENT_25E
	const EVENT_25F
	const EVENT_260
	const EVENT_261
	const EVENT_262
	const EVENT_263
	const EVENT_264
	const EVENT_265
	const EVENT_266
	const EVENT_267
	const EVENT_268
	const EVENT_269
	const EVENT_26A
	const EVENT_26B
	const EVENT_26C
	const EVENT_26D
	const EVENT_26E
	const EVENT_26F
	const EVENT_270
	const EVENT_271
	const EVENT_272
	const EVENT_273
	const EVENT_274
	const EVENT_275
	const EVENT_276
	const EVENT_277
	const EVENT_278
	const EVENT_279
	const EVENT_27A
	const EVENT_27B
	const EVENT_27C
	const EVENT_27D
	const EVENT_27E
	const EVENT_27F
	const EVENT_280
	const EVENT_281
	const EVENT_282
	const EVENT_283
	const EVENT_284
	const EVENT_285
	const EVENT_286
	const EVENT_287
	const EVENT_288
	const EVENT_289
	const EVENT_28A
	const EVENT_28B
	const EVENT_28C
	const EVENT_28D
	const EVENT_28E
	const EVENT_28F
	const EVENT_290
	const EVENT_291
	const EVENT_292
	const EVENT_293
	const EVENT_294
	const EVENT_295
	const EVENT_296
	const EVENT_297
	const EVENT_298
	const EVENT_299
	const EVENT_29A
	const EVENT_29B
	const EVENT_29C
	const EVENT_29D
	const EVENT_29E
	const EVENT_29F
	const EVENT_2A0
	const EVENT_2A1
	const EVENT_2A2
	const EVENT_2A3
	const EVENT_2A4
	const EVENT_2A5
	const EVENT_2A6
	const EVENT_2A7
	const EVENT_2A8
	const EVENT_2A9
	const EVENT_2AA
	const EVENT_2AB
	const EVENT_2AC
	const EVENT_2AD
	const EVENT_2AE
	const EVENT_2AF
	const EVENT_2B0
	const EVENT_2B1
	const EVENT_2B2
	const EVENT_2B3
	const EVENT_2B4
	const EVENT_2B5
	const EVENT_2B6
	const EVENT_2B7
	const EVENT_2B8
	const EVENT_2B9
	const EVENT_2BA
	const EVENT_2BB
	const EVENT_2BC
	const EVENT_2BD
	const EVENT_2BE
	const EVENT_2BF
	const EVENT_2C0
	const EVENT_2C1
	const EVENT_2C2
	const EVENT_2C3
	const EVENT_2C4
	const EVENT_2C5
	const EVENT_2C6
	const EVENT_2C7
	const EVENT_2C8
	const EVENT_2C9
	const EVENT_2CA
	const EVENT_2CB
	const EVENT_2CC
	const EVENT_2CD
	const EVENT_2CE
	const EVENT_2CF
	const EVENT_2D0
	const EVENT_2D1
	const EVENT_2D2
	const EVENT_2D3
	const EVENT_2D4
	const EVENT_2D5
	const EVENT_2D6
	const EVENT_2D7
	const EVENT_2D8
	const EVENT_2D9
	const EVENT_2DA
	const EVENT_2DB
	const EVENT_2DC
	const EVENT_2DD
	const EVENT_2DE
	const EVENT_2DF
	const EVENT_2E0
	const EVENT_2E1
	const EVENT_2E2
	const EVENT_2E3
	const EVENT_2E4
	const EVENT_2E5
	const EVENT_2E6
	const EVENT_2E7
	const EVENT_2E8
	const EVENT_2E9
	const EVENT_2EA
	const EVENT_2EB
	const EVENT_2EC
	const EVENT_2ED
	const EVENT_2EE
	const EVENT_2EF
	const EVENT_2F0
	const EVENT_2F1
	const EVENT_2F2
	const EVENT_2F3
	const EVENT_2F4
	const EVENT_2F5
	const EVENT_2F6
	const EVENT_2F7
	const EVENT_2F8
	const EVENT_2F9
	const EVENT_2FA
	const EVENT_2FB
	const EVENT_2FC
	const EVENT_2FD
	const EVENT_2FE
	const EVENT_2FF
	const EVENT_300
	const EVENT_301
	const EVENT_302
	const EVENT_303
	const EVENT_304
	const EVENT_305
	const EVENT_306
	const EVENT_307
	const EVENT_308
	const EVENT_309
	const EVENT_30A
	const EVENT_30B
	const EVENT_30C
	const EVENT_30D
	const EVENT_30E
	const EVENT_30F
	const EVENT_310
	const EVENT_311
	const EVENT_312
	const EVENT_313
	const EVENT_314
	const EVENT_315
	const EVENT_316
	const EVENT_317
	const EVENT_318
	const EVENT_319
	const EVENT_31A
	const EVENT_31B
	const EVENT_31C
	const EVENT_31D
	const EVENT_31E
	const EVENT_31F
	const EVENT_320
	const EVENT_321
	const EVENT_322
	const EVENT_323
	const EVENT_324
	const EVENT_325
	const EVENT_326
	const EVENT_327
	const EVENT_328
	const EVENT_329
	const EVENT_32A
	const EVENT_32B
	const EVENT_32C
	const EVENT_32D
	const EVENT_32E
	const EVENT_32F
	const EVENT_330
	const EVENT_331
	const EVENT_332
	const EVENT_333
	const EVENT_334
	const EVENT_335
	const EVENT_336
	const EVENT_337
	const EVENT_338
	const EVENT_339
	const EVENT_33A
	const EVENT_33B
	const EVENT_33C
	const EVENT_33D
	const EVENT_33E
	const EVENT_33F
	const EVENT_340
	const EVENT_341
	const EVENT_342
	const EVENT_343
	const EVENT_344
	const EVENT_345
	const EVENT_346
	const EVENT_347
	const EVENT_348
	const EVENT_349
	const EVENT_34A
	const EVENT_34B
	const EVENT_34C
	const EVENT_34D
	const EVENT_34E
	const EVENT_34F
	const EVENT_350
	const EVENT_351
	const EVENT_352
	const EVENT_353
	const EVENT_354
	const EVENT_355
	const EVENT_356
	const EVENT_357
	const EVENT_358
	const EVENT_359
	const EVENT_35A
	const EVENT_35B
	const EVENT_35C
	const EVENT_35D
	const EVENT_35E
	const EVENT_35F
	const EVENT_360
	const EVENT_361
	const EVENT_362
	const EVENT_363
	const EVENT_364
	const EVENT_365
	const EVENT_366
	const EVENT_367
	const EVENT_368
	const EVENT_369
	const EVENT_36A
	const EVENT_36B
	const EVENT_36C
	const EVENT_36D
	const EVENT_36E
	const EVENT_36F
	const EVENT_370
	const EVENT_371
	const EVENT_372
	const EVENT_373
	const EVENT_374
	const EVENT_375
	const EVENT_376
	const EVENT_377
	const EVENT_378
	const EVENT_379
	const EVENT_37A
	const EVENT_37B
	const EVENT_37C
	const EVENT_37D
	const EVENT_37E
	const EVENT_37F
	const EVENT_380
	const EVENT_381
	const EVENT_382
	const EVENT_383
	const EVENT_384
	const EVENT_385
	const EVENT_386
	const EVENT_387
	const EVENT_388
	const EVENT_389
	const EVENT_38A
	const EVENT_38B
	const EVENT_38C
	const EVENT_38D
	const EVENT_38E
	const EVENT_38F
	const EVENT_390
	const EVENT_391
	const EVENT_392
	const EVENT_393
	const EVENT_394
	const EVENT_395
	const EVENT_396
	const EVENT_397
	const EVENT_398
	const EVENT_399
	const EVENT_39A
	const EVENT_39B
	const EVENT_39C
	const EVENT_39D
	const EVENT_39E
	const EVENT_39F
	const EVENT_3A0
	const EVENT_3A1
	const EVENT_3A2
	const EVENT_3A3
	const EVENT_3A4
	const EVENT_3A5
	const EVENT_3A6
	const EVENT_3A7
	const EVENT_3A8
	const EVENT_3A9
	const EVENT_3AA
	const EVENT_3AB
	const EVENT_3AC
	const EVENT_3AD
	const EVENT_3AE
	const EVENT_3AF
	const EVENT_3B0
	const EVENT_3B1
	const EVENT_3B2
	const EVENT_3B3
	const EVENT_3B4
	const EVENT_3B5
	const EVENT_3B6
	const EVENT_3B7
	const EVENT_3B8
	const EVENT_3B9
	const EVENT_3BA
	const EVENT_3BB
	const EVENT_3BC
	const EVENT_3BD
	const EVENT_3BE
	const EVENT_3BF
	const EVENT_3C0
	const EVENT_3C1
	const EVENT_3C2
	const EVENT_3C3
	const EVENT_3C4
	const EVENT_3C5
	const EVENT_3C6
	const EVENT_3C7
	const EVENT_3C8
	const EVENT_3C9
	const EVENT_3CA
	const EVENT_3CB
	const EVENT_3CC
	const EVENT_3CD
	const EVENT_3CE
	const EVENT_3CF
	const EVENT_3D0
	const EVENT_3D1
	const EVENT_3D2
	const EVENT_3D3
	const EVENT_3D4
	const EVENT_3D5
	const EVENT_3D6
	const EVENT_3D7
	const EVENT_3D8
	const EVENT_3D9
	const EVENT_3DA
	const EVENT_3DB
	const EVENT_3DC
	const EVENT_3DD
	const EVENT_3DE
	const EVENT_3DF
	const EVENT_3E0
	const EVENT_3E1
	const EVENT_3E2
	const EVENT_3E3
	const EVENT_3E4
	const EVENT_3E5
	const EVENT_3E6
	const EVENT_3E7
	const EVENT_3E8
	const EVENT_3E9
	const EVENT_3EA
	const EVENT_3EB
	const EVENT_3EC
	const EVENT_3ED
	const EVENT_3EE
	const EVENT_3EF
	const EVENT_3F0
	const EVENT_3F1
	const EVENT_3F2
	const EVENT_3F3
	const EVENT_3F4
	const EVENT_3F5
	const EVENT_3F6
	const EVENT_3F7
	const EVENT_3F8
	const EVENT_3F9
	const EVENT_3FA
	const EVENT_3FB
	const EVENT_3FC
	const EVENT_3FD
	const EVENT_3FE
	const EVENT_3FF
	const EVENT_400
	const EVENT_401
	const EVENT_402
	const EVENT_403
	const EVENT_404
	const EVENT_405
	const EVENT_406
	const EVENT_407
	const EVENT_408
	const EVENT_409
	const EVENT_40A
	const EVENT_40B
	const EVENT_40C
	const EVENT_40D
	const EVENT_40E
	const EVENT_40F
	const EVENT_410
	const EVENT_411
	const EVENT_412
	const EVENT_413
	const EVENT_414
	const EVENT_415
	const EVENT_416
	const EVENT_417
	const EVENT_418
	const EVENT_419
	const EVENT_41A
	const EVENT_41B
	const EVENT_41C
	const EVENT_41D
	const EVENT_41E
	const EVENT_41F
	const EVENT_420
	const EVENT_421
	const EVENT_422
	const EVENT_423
	const EVENT_424
	const EVENT_425
	const EVENT_426
	const EVENT_427
	const EVENT_428
	const EVENT_429
	const EVENT_42A
	const EVENT_42B
	const EVENT_42C
	const EVENT_42D
	const EVENT_42E
	const EVENT_42F
	const EVENT_430
	const EVENT_431
	const EVENT_432
	const EVENT_433
	const EVENT_434
	const EVENT_435
	const EVENT_436
	const EVENT_437
	const EVENT_438
	const EVENT_439
	const EVENT_43A
	const EVENT_43B
	const EVENT_43C
	const EVENT_43D
	const EVENT_43E
	const EVENT_43F
	const EVENT_440
	const EVENT_441
	const EVENT_442
	const EVENT_443
	const EVENT_444
	const EVENT_445
	const EVENT_446
	const EVENT_447
	const EVENT_448
	const EVENT_449
	const EVENT_44A
	const EVENT_44B
	const EVENT_44C
	const EVENT_44D
	const EVENT_44E
	const EVENT_44F
	const EVENT_450
	const EVENT_451
	const EVENT_452
	const EVENT_453
	const EVENT_454
	const EVENT_455
	const EVENT_456
	const EVENT_457
	const EVENT_458
	const EVENT_459
	const EVENT_45A
	const EVENT_45B
	const EVENT_45C
	const EVENT_45D
	const EVENT_45E
	const EVENT_45F
	const EVENT_460
	const EVENT_461
	const EVENT_462
	const EVENT_463
	const EVENT_464
	const EVENT_465
	const EVENT_466
	const EVENT_467
	const EVENT_468
	const EVENT_469
	const EVENT_46A
	const EVENT_46B
	const EVENT_46C
	const EVENT_46D
	const EVENT_46E
	const EVENT_46F
	const EVENT_470
	const EVENT_471
	const EVENT_472
	const EVENT_473
	const EVENT_474
	const EVENT_475
	const EVENT_476
	const EVENT_477
	const EVENT_478
	const EVENT_479
	const EVENT_47A
	const EVENT_47B
	const EVENT_47C
	const EVENT_47D
	const EVENT_47E
	const EVENT_47F
	const EVENT_480
	const EVENT_481
	const EVENT_482
	const EVENT_483
	const EVENT_484
	const EVENT_485
	const EVENT_486
	const EVENT_487
	const EVENT_488
	const EVENT_489
	const EVENT_48A
	const EVENT_48B
	const EVENT_48C
	const EVENT_48D
	const EVENT_48E
	const EVENT_48F
	const EVENT_490
	const EVENT_491
	const EVENT_492
	const EVENT_493
	const EVENT_494
	const EVENT_495
	const EVENT_496
	const EVENT_497
	const EVENT_498
	const EVENT_499
	const EVENT_49A
	const EVENT_49B
	const EVENT_49C
	const EVENT_49D
	const EVENT_49E
	const EVENT_49F
	const EVENT_4A0
	const EVENT_4A1
	const EVENT_4A2
	const EVENT_4A3
	const EVENT_4A4
	const EVENT_4A5
	const EVENT_4A6
	const EVENT_4A7
	const EVENT_4A8
	const EVENT_4A9
	const EVENT_4AA
	const EVENT_4AB
	const EVENT_4AC
	const EVENT_4AD
	const EVENT_4AE
	const EVENT_4AF
	const EVENT_4B0
	const EVENT_4B1
	const EVENT_4B2
	const EVENT_4B3
	const EVENT_4B4
	const EVENT_4B5
	const EVENT_4B6
	const EVENT_4B7
	const EVENT_4B8
	const EVENT_4B9
	const EVENT_4BA
	const EVENT_4BB
	const EVENT_4BC
	const EVENT_4BD
	const EVENT_4BE
	const EVENT_4BF
	const EVENT_4C0
	const EVENT_4C1
	const EVENT_4C2
	const EVENT_4C3
	const EVENT_4C4
	const EVENT_4C5
	const EVENT_4C6
	const EVENT_4C7
	const EVENT_4C8
	const EVENT_4C9
	const EVENT_4CA
	const EVENT_4CB
	const EVENT_4CC
	const EVENT_4CD
	const EVENT_4CE
	const EVENT_4CF
	const EVENT_4D0
	const EVENT_4D1
	const EVENT_4D2
	const EVENT_4D3
	const EVENT_4D4
	const EVENT_4D5
	const EVENT_4D6
	const EVENT_4D7
	const EVENT_4D8
	const EVENT_4D9
	const EVENT_4DA
	const EVENT_4DB
	const EVENT_4DC
	const EVENT_4DD
	const EVENT_4DE
	const EVENT_4DF
	const EVENT_4E0
	const EVENT_4E1
	const EVENT_4E2
	const EVENT_4E3
	const EVENT_4E4
	const EVENT_4E5
	const EVENT_4E6
	const EVENT_4E7
	const EVENT_4E8
	const EVENT_4E9
	const EVENT_4EA
	const EVENT_4EB
	const EVENT_4EC
	const EVENT_4ED
	const EVENT_4EE
	const EVENT_4EF
	const EVENT_4F0
	const EVENT_4F1
	const EVENT_4F2
	const EVENT_4F3
	const EVENT_4F4
	const EVENT_4F5
	const EVENT_4F6
	const EVENT_4F7
	const EVENT_4F8
	const EVENT_4F9
	const EVENT_4FA
	const EVENT_4FB
	const EVENT_4FC
	const EVENT_4FD
	const EVENT_4FE
	const EVENT_4FF
	const EVENT_500
	const EVENT_501
	const EVENT_502
	const EVENT_503
	const EVENT_504
	const EVENT_505
	const EVENT_506
	const EVENT_507
	const EVENT_508
	const EVENT_509
	const EVENT_50A
	const EVENT_50B
	const EVENT_50C
	const EVENT_50D
	const EVENT_50E
	const EVENT_50F
	const EVENT_510
	const EVENT_511
	const EVENT_512
	const EVENT_513
	const EVENT_514
	const EVENT_515
	const EVENT_516
	const EVENT_517
	const EVENT_518
	const EVENT_519
	const EVENT_51A
	const EVENT_51B
	const EVENT_51C
	const EVENT_51D
	const EVENT_51E
	const EVENT_51F
	const EVENT_520
	const EVENT_521
	const EVENT_522
	const EVENT_523
	const EVENT_524
	const EVENT_525
	const EVENT_526
	const EVENT_527
	const EVENT_528
	const EVENT_529
	const EVENT_52A
	const EVENT_52B
	const EVENT_52C
	const EVENT_52D
	const EVENT_52E
	const EVENT_52F
	const EVENT_530
	const EVENT_531
	const EVENT_532
	const EVENT_533
	const EVENT_534
	const EVENT_535
	const EVENT_536
	const EVENT_537
	const EVENT_538
	const EVENT_539
	const EVENT_53A
	const EVENT_53B
	const EVENT_53C
	const EVENT_53D
	const EVENT_53E
	const EVENT_53F
	const EVENT_540
	const EVENT_541
	const EVENT_542
	const EVENT_543
	const EVENT_544
	const EVENT_545
	const EVENT_546
	const EVENT_547
	const EVENT_548
	const EVENT_549
	const EVENT_54A
	const EVENT_54B
	const EVENT_54C
	const EVENT_54D
	const EVENT_54E
	const EVENT_54F
	const EVENT_550
	const EVENT_551
	const EVENT_552
	const EVENT_553
	const EVENT_554
	const EVENT_555
	const EVENT_556
	const EVENT_557
	const EVENT_558
	const EVENT_559
	const EVENT_55A
	const EVENT_55B
	const EVENT_55C
	const EVENT_55D
	const EVENT_55E
	const EVENT_55F
	const EVENT_560
	const EVENT_561
	const EVENT_562
	const EVENT_563
	const EVENT_564
	const EVENT_565
	const EVENT_566
	const EVENT_567
	const EVENT_568
	const EVENT_569
	const EVENT_56A
	const EVENT_56B
	const EVENT_56C
	const EVENT_56D
	const EVENT_56E
	const EVENT_56F
	const EVENT_570
	const EVENT_571
	const EVENT_572
	const EVENT_573
	const EVENT_574
	const EVENT_575
	const EVENT_576
	const EVENT_577
	const EVENT_578
	const EVENT_579
	const EVENT_57A
	const EVENT_57B
	const EVENT_57C
	const EVENT_57D
	const EVENT_57E
	const EVENT_57F
	const EVENT_580
	const EVENT_581
	const EVENT_582
	const EVENT_583
	const EVENT_584
	const EVENT_585
	const EVENT_586
	const EVENT_587
	const EVENT_588
	const EVENT_589
	const EVENT_58A
	const EVENT_58B
	const EVENT_58C
	const EVENT_58D
	const EVENT_58E
	const EVENT_58F
	const EVENT_590
	const EVENT_591
	const EVENT_592
	const EVENT_593
	const EVENT_594
	const EVENT_595
	const EVENT_596
	const EVENT_597
	const EVENT_598
	const EVENT_599
	const EVENT_59A
	const EVENT_59B
	const EVENT_59C
	const EVENT_59D
	const EVENT_59E
	const EVENT_59F
	const EVENT_5A0
	const EVENT_5A1
	const EVENT_5A2
	const EVENT_5A3
	const EVENT_5A4
	const EVENT_5A5
	const EVENT_5A6
	const EVENT_5A7
	const EVENT_5A8
	const EVENT_5A9
	const EVENT_5AA
	const EVENT_5AB
	const EVENT_5AC
	const EVENT_5AD
	const EVENT_5AE
	const EVENT_5AF
	const EVENT_5B0
	const EVENT_5B1
	const EVENT_5B2
	const EVENT_5B3
	const EVENT_5B4
	const EVENT_5B5
	const EVENT_5B6
	const EVENT_5B7
	const EVENT_5B8
	const EVENT_5B9
	const EVENT_5BA
	const EVENT_5BB
	const EVENT_5BC
	const EVENT_5BD
	const EVENT_5BE
	const EVENT_5BF
	const EVENT_5C0
	const EVENT_5C1
	const EVENT_5C2
	const EVENT_5C3
	const EVENT_5C4
	const EVENT_5C5
	const EVENT_5C6
	const EVENT_5C7
	const EVENT_5C8
	const EVENT_5C9
	const EVENT_5CA
	const EVENT_5CB
	const EVENT_5CC
	const EVENT_5CD
	const EVENT_5CE
	const EVENT_5CF
	const EVENT_5D0
	const EVENT_5D1
	const EVENT_5D2
	const EVENT_5D3
	const EVENT_5D4
	const EVENT_5D5
	const EVENT_5D6
	const EVENT_5D7
	const EVENT_5D8
	const EVENT_5D9
	const EVENT_5DA
	const EVENT_5DB
	const EVENT_5DC
	const EVENT_5DD
	const EVENT_5DE
	const EVENT_5DF
	const EVENT_5E0
	const EVENT_5E1
	const EVENT_5E2
	const EVENT_5E3
	const EVENT_5E4
	const EVENT_5E5
	const EVENT_5E6
	const EVENT_5E7
	const EVENT_5E8
	const EVENT_5E9
	const EVENT_5EA
	const EVENT_5EB
	const EVENT_5EC
	const EVENT_5ED
	const EVENT_5EE
	const EVENT_5EF
	const EVENT_5F0
	const EVENT_5F1
	const EVENT_5F2
	const EVENT_5F3
	const EVENT_5F4
	const EVENT_5F5
	const EVENT_5F6
	const EVENT_5F7
	const EVENT_5F8
	const EVENT_5F9
	const EVENT_5FA
	const EVENT_5FB
	const EVENT_5FC
	const EVENT_5FD
	const EVENT_5FE
	const EVENT_5FF
	const EVENT_600
	const EVENT_601
	const EVENT_602
	const EVENT_603
	const EVENT_604
	const EVENT_605
	const EVENT_606
	const EVENT_607
	const EVENT_608
	const EVENT_609
	const EVENT_60A
	const EVENT_60B
	const EVENT_60C
	const EVENT_60D
	const EVENT_60E
	const EVENT_60F
	const EVENT_610
	const EVENT_611
	const EVENT_612
	const EVENT_613
	const EVENT_614
	const EVENT_615
	const EVENT_616
	const EVENT_617
	const EVENT_618
	const EVENT_619
	const EVENT_61A
	const EVENT_61B
	const EVENT_61C
	const EVENT_61D
	const EVENT_61E
	const EVENT_61F
	const EVENT_620
	const EVENT_621
	const EVENT_622
	const EVENT_623
	const EVENT_624
	const EVENT_625
	const EVENT_626
	const EVENT_627
	const EVENT_628
	const EVENT_629
	const EVENT_62A
	const EVENT_62B
	const EVENT_62C
	const EVENT_62D
	const EVENT_62E
	const EVENT_62F
	const EVENT_630
	const EVENT_631
	const EVENT_632
	const EVENT_633
	const EVENT_634
	const EVENT_635
	const EVENT_636
	const EVENT_637
	const EVENT_638
	const EVENT_639
	const EVENT_63A
	const EVENT_63B
	const EVENT_63C
	const EVENT_63D
	const EVENT_63E
	const EVENT_63F
	const EVENT_640
	const EVENT_641
	const EVENT_642
	const EVENT_643
	const EVENT_644
	const EVENT_645
	const EVENT_646
	const EVENT_647
	const EVENT_648
	const EVENT_649
	const EVENT_64A
	const EVENT_64B
	const EVENT_64C
	const EVENT_64D
	const EVENT_64E
	const EVENT_64F
	const EVENT_650
	const EVENT_651
	const EVENT_652
	const EVENT_653
	const EVENT_654
	const EVENT_655
	const EVENT_656
	const EVENT_657
	const EVENT_658
	const EVENT_659
	const EVENT_65A
	const EVENT_65B
	const EVENT_65C
	const EVENT_65D
	const EVENT_65E
	const EVENT_65F
	const EVENT_660
	const EVENT_661
	const EVENT_662
	const EVENT_663
	const EVENT_664
	const EVENT_665
	const EVENT_666
	const EVENT_667
	const EVENT_668
	const EVENT_669
	const EVENT_66A
	const EVENT_66B
	const EVENT_66C
	const EVENT_66D
	const EVENT_66E
	const EVENT_66F
	const EVENT_670
	const EVENT_671
	const EVENT_672
	const EVENT_673
	const EVENT_674
	const EVENT_675
	const EVENT_676
	const EVENT_677
	const EVENT_678
	const EVENT_679
	const EVENT_67A
	const EVENT_67B
	const EVENT_67C
	const EVENT_67D
	const EVENT_67E
	const EVENT_67F
	const EVENT_680
	const EVENT_681
	const EVENT_682
	const EVENT_683
	const EVENT_684
	const EVENT_685
	const EVENT_686
	const EVENT_687
	const EVENT_688
	const EVENT_689
	const EVENT_68A
	const EVENT_68B
	const EVENT_68C
	const EVENT_68D
	const EVENT_68E
	const EVENT_68F
	const EVENT_690
	const EVENT_691
	const EVENT_692
	const EVENT_693
	const EVENT_694
	const EVENT_695
	const EVENT_696
	const EVENT_697
	const EVENT_698
	const EVENT_699
	const EVENT_69A
	const EVENT_69B
	const EVENT_69C
	const EVENT_69D
	const EVENT_69E
	const EVENT_69F
	const EVENT_6A0
	const EVENT_6A1
	const EVENT_6A2
	const EVENT_6A3
	const EVENT_6A4
	const EVENT_6A5
	const EVENT_6A6
	const EVENT_6A7
	const EVENT_6A8
	const EVENT_6A9
	const EVENT_6AA
	const EVENT_6AB
	const EVENT_6AC
	const EVENT_6AD
	const EVENT_6AE
	const EVENT_6AF
	const EVENT_6B0
	const EVENT_6B1
	const EVENT_6B2
	const EVENT_6B3
	const EVENT_6B4
	const EVENT_6B5
	const EVENT_6B6
	const EVENT_6B7
	const EVENT_6B8
	const EVENT_6B9
	const EVENT_6BA
	const EVENT_6BB
	const EVENT_6BC
	const EVENT_6BD
	const EVENT_6BE
	const EVENT_6BF
	const EVENT_6C0
	const EVENT_6C1
	const EVENT_6C2
	const EVENT_6C3
	const EVENT_6C4
	const EVENT_6C5
	const EVENT_6C6
	const EVENT_6C7
	const EVENT_6C8
	const EVENT_6C9
	const EVENT_6CA
	const EVENT_6CB
	const EVENT_6CC
	const EVENT_6CD
	const EVENT_6CE
	const EVENT_6CF
	const EVENT_6D0
	const EVENT_6D1
	const EVENT_6D2
	const EVENT_6D3
	const EVENT_6D4
	const EVENT_6D5
	const EVENT_6D6
	const EVENT_6D7
	const EVENT_6D8
	const EVENT_6D9
	const EVENT_6DA
	const EVENT_6DB
	const EVENT_6DC
	const EVENT_6DD
	const EVENT_6DE
	const EVENT_6DF
	const EVENT_6E0
	const EVENT_6E1
	const EVENT_6E2
	const EVENT_6E3
	const EVENT_6E4
	const EVENT_6E5
	const EVENT_6E6
	const EVENT_6E7
	const EVENT_6E8
	const EVENT_6E9
	const EVENT_6EA
	const EVENT_6EB
	const EVENT_6EC
	const EVENT_6ED
	const EVENT_6EE
	const EVENT_6EF
	const EVENT_6F0
	const EVENT_6F1
	const EVENT_6F2
	const EVENT_6F3
	const EVENT_6F4
	const EVENT_6F5
	const EVENT_6F6
	const EVENT_6F7
	const EVENT_6F8
	const EVENT_6F9
	const EVENT_6FA
	const EVENT_6FB
	const EVENT_6FC
	const EVENT_6FD
	const EVENT_6FE
	const EVENT_6FF
	const EVENT_700
	const EVENT_701
	const EVENT_702
	const EVENT_703
	const EVENT_704
	const EVENT_705
	const EVENT_706
	const EVENT_707
	const EVENT_708
	const EVENT_709
	const EVENT_70A
	const EVENT_70B
	const EVENT_70C
	const EVENT_70D
	const EVENT_70E
	const EVENT_70F
	const EVENT_710
	const EVENT_711
	const EVENT_712
	const EVENT_713
	const EVENT_714
	const EVENT_715
	const EVENT_716
	const EVENT_717
	const EVENT_718
	const EVENT_719
	const EVENT_71A
	const EVENT_71B
	const EVENT_71C
	const EVENT_71D
	const EVENT_71E
	const EVENT_71F
	const EVENT_720
	const EVENT_721
	const EVENT_722
	const EVENT_723
	const EVENT_724
	const EVENT_725
	const EVENT_726
	const EVENT_727
	const EVENT_728
	const EVENT_729
	const EVENT_72A
	const EVENT_72B
	const EVENT_72C
	const EVENT_72D
	const EVENT_72E
	const EVENT_72F
	const EVENT_730
	const EVENT_731
	const EVENT_732
	const EVENT_733
	const EVENT_734
	const EVENT_735
	const EVENT_736
	const EVENT_737
	const EVENT_738
	const EVENT_739
	const EVENT_73A
	const EVENT_73B
	const EVENT_73C
	const EVENT_73D
	const EVENT_73E
	const EVENT_73F
	const EVENT_740
	const EVENT_741
	const EVENT_742
	const EVENT_743
	const EVENT_744
	const EVENT_745
	const EVENT_746
	const EVENT_747
	const EVENT_748
	const EVENT_749
	const EVENT_74A
	const EVENT_74B
	const EVENT_74C
	const EVENT_74D
	const EVENT_74E
	const EVENT_74F
	const EVENT_750
	const EVENT_751
	const EVENT_752
	const EVENT_753
	const EVENT_754
	const EVENT_755
	const EVENT_756
	const EVENT_757
	const EVENT_758
	const EVENT_759
	const EVENT_75A
	const EVENT_75B
	const EVENT_75C
	const EVENT_75D
	const EVENT_75E
	const EVENT_75F
	const EVENT_760
	const EVENT_761
	const EVENT_762
	const EVENT_763
	const EVENT_764
	const EVENT_765
	const EVENT_766
	const EVENT_767
	const EVENT_768
	const EVENT_769
	const EVENT_76A
	const EVENT_76B
	const EVENT_76C
	const EVENT_76D
	const EVENT_76E
	const EVENT_76F
	const EVENT_770
	const EVENT_771
	const EVENT_772
	const EVENT_773
	const EVENT_774
	const EVENT_775
	const EVENT_776
	const EVENT_777
	const EVENT_778
	const EVENT_779
	const EVENT_77A
	const EVENT_77B
	const EVENT_77C
	const EVENT_77D
	const EVENT_77E
	const EVENT_77F
	const EVENT_780
	const EVENT_781
	const EVENT_782
	const EVENT_783
	const EVENT_784
	const EVENT_785
	const EVENT_786
	const EVENT_787
	const EVENT_788
	const EVENT_789
	const EVENT_78A
	const EVENT_78B
	const EVENT_78C
	const EVENT_78D
	const EVENT_78E
	const EVENT_78F
	const EVENT_790
	const EVENT_791
	const EVENT_792
	const EVENT_793
	const EVENT_794
	const EVENT_795
	const EVENT_796
	const EVENT_797
	const EVENT_798
	const EVENT_799
	const EVENT_79A
	const EVENT_79B
	const EVENT_79C
	const EVENT_79D
	const EVENT_79E
	const EVENT_79F
	const EVENT_7A0
	const EVENT_7A1
	const EVENT_7A2
	const EVENT_7A3
	const EVENT_7A4
	const EVENT_7A5
	const EVENT_7A6
	const EVENT_7A7
	const EVENT_7A8
	const EVENT_7A9
	const EVENT_7AA
	const EVENT_7AB
	const EVENT_7AC
	const EVENT_7AD
	const EVENT_7AE
	const EVENT_7AF
	const EVENT_7B0
	const EVENT_7B1
	const EVENT_7B2
	const EVENT_7B3
	const EVENT_7B4
	const EVENT_7B5
	const EVENT_7B6
	const EVENT_7B7
	const EVENT_7B8
	const EVENT_7B9
	const EVENT_7BA
	const EVENT_7BB
	const EVENT_7BC
	const EVENT_7BD
	const EVENT_7BE
	const EVENT_7BF
	const EVENT_7C0
	const EVENT_7C1
	const EVENT_7C2
	const EVENT_7C3
	const EVENT_7C4
	const EVENT_7C5
	const EVENT_7C6
	const EVENT_7C7
	const EVENT_7C8
	const EVENT_7C9
	const EVENT_7CA
	const EVENT_7CB
	const EVENT_7CC
	const EVENT_7CD
	const EVENT_7CE
	const EVENT_7CF
	const EVENT_7D0
	const EVENT_7D1
	const EVENT_7D2
	const EVENT_7D3
	const EVENT_7D4
	const EVENT_7D5
	const EVENT_7D6
	const EVENT_7D7
	const EVENT_7D8
	const EVENT_7D9
	const EVENT_7DA
	const EVENT_7DB
	const EVENT_7DC
	const EVENT_7DD
	const EVENT_7DE
	const EVENT_7DF
	const EVENT_7E0
	const EVENT_7E1
	const EVENT_7E2
	const EVENT_7E3
	const EVENT_7E4
	const EVENT_7E5
	const EVENT_7E6
	const EVENT_7E7
	const EVENT_7E8
	const EVENT_7E9
	const EVENT_7EA
	const EVENT_7EB
	const EVENT_7EC
	const EVENT_7ED
	const EVENT_7EE
	const EVENT_7EF
	const EVENT_7F0
	const EVENT_7F1
	const EVENT_7F2
	const EVENT_7F3
	const EVENT_7F4
	const EVENT_7F5
	const EVENT_7F6
	const EVENT_7F7
	const EVENT_7F8
	const EVENT_7F9
	const EVENT_7FA
	const EVENT_7FB
	const EVENT_7FC
	const EVENT_7FD
	const EVENT_7FE
	const EVENT_7FF
	const EVENT_800
	const EVENT_801
	const EVENT_802
	const EVENT_803
	const EVENT_804
	const EVENT_805
	const EVENT_806
	const EVENT_807
	const EVENT_808
	const EVENT_809
	const EVENT_80A
	const EVENT_80B
	const EVENT_80C
	const EVENT_80D
	const EVENT_80E
	const EVENT_80F
	const EVENT_810
	const EVENT_811
	const EVENT_812
	const EVENT_813
	const EVENT_814
	const EVENT_815
	const EVENT_816
	const EVENT_817
	const EVENT_818
	const EVENT_819
	const EVENT_81A
	const EVENT_81B
	const EVENT_81C
	const EVENT_81D
	const EVENT_81E
	const EVENT_81F
	const EVENT_820
	const EVENT_821
	const EVENT_822
	const EVENT_823
	const EVENT_824
	const EVENT_825
	const EVENT_826
	const EVENT_827
	const EVENT_828
	const EVENT_829
	const EVENT_82A
	const EVENT_82B
	const EVENT_82C
	const EVENT_82D
	const EVENT_82E
	const EVENT_82F
	const EVENT_830
	const EVENT_831
	const EVENT_832
	const EVENT_833
	const EVENT_834
	const EVENT_835
	const EVENT_836
	const EVENT_837
	const EVENT_838
	const EVENT_839
	const EVENT_83A
	const EVENT_83B
	const EVENT_83C
	const EVENT_83D
	const EVENT_83E
	const EVENT_83F
	const EVENT_840
	const EVENT_841
	const EVENT_842
	const EVENT_843
	const EVENT_844
	const EVENT_845
	const EVENT_846
	const EVENT_847
	const EVENT_848
	const EVENT_849
	const EVENT_84A
	const EVENT_84B
	const EVENT_84C
	const EVENT_84D
	const EVENT_84E
	const EVENT_84F
	const EVENT_850
	const EVENT_851
	const EVENT_852
	const EVENT_853
	const EVENT_854
	const EVENT_855
	const EVENT_856
	const EVENT_857
	const EVENT_858
	const EVENT_859
	const EVENT_85A
	const EVENT_85B
	const EVENT_85C
	const EVENT_85D
	const EVENT_85E
	const EVENT_85F
	const EVENT_860
	const EVENT_861
	const EVENT_862
	const EVENT_863
	const EVENT_864
	const EVENT_865
	const EVENT_866
	const EVENT_867
	const EVENT_868
	const EVENT_869
	const EVENT_86A
	const EVENT_86B
	const EVENT_86C
	const EVENT_86D
	const EVENT_86E
	const EVENT_86F
	const EVENT_870
	const EVENT_871
	const EVENT_872
	const EVENT_873
	const EVENT_874
	const EVENT_875
	const EVENT_876
	const EVENT_877
	const EVENT_878
	const EVENT_879
	const EVENT_87A
	const EVENT_87B
	const EVENT_87C
	const EVENT_87D
	const EVENT_87E
	const EVENT_87F
	const EVENT_880
	const EVENT_881
	const EVENT_882
	const EVENT_883
	const EVENT_884
	const EVENT_885
	const EVENT_886
	const EVENT_887
	const EVENT_888
	const EVENT_889
	const EVENT_88A
	const EVENT_88B
	const EVENT_88C
	const EVENT_88D
	const EVENT_88E
	const EVENT_88F
	const EVENT_890
	const EVENT_891
	const EVENT_892
	const EVENT_893
	const EVENT_894
	const EVENT_895
	const EVENT_896
	const EVENT_897
	const EVENT_898
	const EVENT_899
	const EVENT_89A
	const EVENT_89B
	const EVENT_89C
	const EVENT_89D
	const EVENT_89E
	const EVENT_89F
	const EVENT_8A0
	const EVENT_8A1
	const EVENT_8A2
	const EVENT_8A3
	const EVENT_8A4
	const EVENT_8A5
	const EVENT_8A6
	const EVENT_8A7
	const EVENT_8A8
	const EVENT_8A9
	const EVENT_8AA
	const EVENT_8AB
	const EVENT_8AC
	const EVENT_8AD
	const EVENT_8AE
	const EVENT_8AF
	const EVENT_8B0
	const EVENT_8B1
	const EVENT_8B2
	const EVENT_8B3
	const EVENT_8B4
	const EVENT_8B5
	const EVENT_8B6
	const EVENT_8B7
	const EVENT_8B8
	const EVENT_8B9
	const EVENT_8BA
	const EVENT_8BB
	const EVENT_8BC
	const EVENT_8BD
	const EVENT_8BE
	const EVENT_8BF
	const EVENT_8C0
	const EVENT_8C1
	const EVENT_8C2
	const EVENT_8C3
	const EVENT_8C4
	const EVENT_8C5
	const EVENT_8C6
	const EVENT_8C7
	const EVENT_8C8
	const EVENT_8C9
	const EVENT_8CA
	const EVENT_8CB
	const EVENT_8CC
	const EVENT_8CD
	const EVENT_8CE
	const EVENT_8CF
	const EVENT_8D0
	const EVENT_8D1
	const EVENT_8D2
	const EVENT_8D3
	const EVENT_8D4
	const EVENT_8D5
	const EVENT_8D6
	const EVENT_8D7
	const EVENT_8D8
	const EVENT_8D9
	const EVENT_8DA
	const EVENT_8DB
	const EVENT_8DC
	const EVENT_8DD
	const EVENT_8DE
	const EVENT_8DF
	const EVENT_8E0
	const EVENT_8E1
	const EVENT_8E2
	const EVENT_8E3
	const EVENT_8E4
	const EVENT_8E5
	const EVENT_8E6
	const EVENT_8E7
	const EVENT_8E8
	const EVENT_8E9
	const EVENT_8EA
	const EVENT_8EB
	const EVENT_8EC
	const EVENT_8ED
	const EVENT_8EE
	const EVENT_8EF
	const EVENT_8F0
	const EVENT_8F1
	const EVENT_8F2
	const EVENT_8F3
	const EVENT_8F4
	const EVENT_8F5
	const EVENT_8F6
	const EVENT_8F7
	const EVENT_8F8
	const EVENT_8F9
	const EVENT_8FA
	const EVENT_8FB
	const EVENT_8FC
	const EVENT_8FD
	const EVENT_8FE
	const EVENT_8FF
	const EVENT_900
	const EVENT_901
	const EVENT_902
	const EVENT_903
	const EVENT_904
	const EVENT_905
	const EVENT_906
	const EVENT_907
	const EVENT_908
	const EVENT_909
	const EVENT_90A
	const EVENT_90B
	const EVENT_90C
	const EVENT_90D
	const EVENT_90E
	const EVENT_90F
	const EVENT_910
	const EVENT_911
	const EVENT_912
	const EVENT_913
	const EVENT_914
	const EVENT_915
	const EVENT_916
	const EVENT_917
	const EVENT_918
	const EVENT_919
	const EVENT_91A
	const EVENT_91B
	const EVENT_91C
	const EVENT_91D
	const EVENT_91E
	const EVENT_91F
	const EVENT_920
	const EVENT_921
	const EVENT_922
	const EVENT_923
	const EVENT_924
	const EVENT_925
	const EVENT_926
	const EVENT_927
	const EVENT_928
	const EVENT_929
	const EVENT_92A
	const EVENT_92B
	const EVENT_92C
	const EVENT_92D
	const EVENT_92E
	const EVENT_92F
	const EVENT_930
	const EVENT_931
	const EVENT_932
	const EVENT_933
	const EVENT_934
	const EVENT_935
	const EVENT_936
	const EVENT_937
	const EVENT_938
	const EVENT_939
	const EVENT_93A
	const EVENT_93B
	const EVENT_93C
	const EVENT_93D
	const EVENT_93E
	const EVENT_93F
	const EVENT_940
	const EVENT_941
	const EVENT_942
	const EVENT_943
	const EVENT_944
	const EVENT_945
	const EVENT_946
	const EVENT_947
	const EVENT_948
	const EVENT_949
	const EVENT_94A
	const EVENT_94B
	const EVENT_94C
	const EVENT_94D
	const EVENT_94E
	const EVENT_94F
	const EVENT_950
	const EVENT_951
	const EVENT_952
	const EVENT_953
	const EVENT_954
	const EVENT_955
	const EVENT_956
	const EVENT_957
	const EVENT_958
	const EVENT_959
	const EVENT_95A
	const EVENT_95B
	const EVENT_95C
	const EVENT_95D
	const EVENT_95E
	const EVENT_95F
	const EVENT_960
	const EVENT_961
	const EVENT_962
	const EVENT_963
	const EVENT_964
	const EVENT_965
	const EVENT_966
	const EVENT_967
	const EVENT_968
	const EVENT_969
	const EVENT_96A
	const EVENT_96B
	const EVENT_96C
	const EVENT_96D
	const EVENT_96E
	const EVENT_96F
	const EVENT_970
	const EVENT_971
	const EVENT_972
	const EVENT_973
	const EVENT_974
	const EVENT_975
	const EVENT_976
	const EVENT_977
	const EVENT_978
	const EVENT_979
	const EVENT_97A
	const EVENT_97B
	const EVENT_97C
	const EVENT_97D
	const EVENT_97E
	const EVENT_97F
	const EVENT_980
	const EVENT_981
	const EVENT_982
	const EVENT_983
	const EVENT_984
	const EVENT_985
	const EVENT_986
	const EVENT_987
	const EVENT_988
	const EVENT_989
	const EVENT_98A
	const EVENT_98B
	const EVENT_98C
	const EVENT_98D
	const EVENT_98E
	const EVENT_98F
	const EVENT_990
	const EVENT_991
	const EVENT_992
	const EVENT_993
	const EVENT_994
	const EVENT_995
	const EVENT_996
	const EVENT_997
	const EVENT_998
	const EVENT_999
	const EVENT_99A
	const EVENT_99B
	const EVENT_99C
	const EVENT_99D
	const EVENT_99E
	const EVENT_99F
	const EVENT_9A0
	const EVENT_9A1
	const EVENT_9A2
	const EVENT_9A3
	const EVENT_9A4
	const EVENT_9A5
	const EVENT_9A6
	const EVENT_9A7
	const EVENT_9A8
	const EVENT_9A9
	const EVENT_9AA
	const EVENT_9AB
	const EVENT_9AC
	const EVENT_9AD
	const EVENT_9AE
	const EVENT_9AF
	const EVENT_9B0
	const EVENT_9B1
	const EVENT_9B2
	const EVENT_9B3
	const EVENT_9B4
	const EVENT_9B5
	const EVENT_9B6
	const EVENT_9B7
	const EVENT_9B8
	const EVENT_9B9
	const EVENT_9BA
	const EVENT_9BB
	const EVENT_9BC
	const EVENT_9BD
	const EVENT_9BE
	const EVENT_9BF
	const EVENT_9C0
	const EVENT_9C1
	const EVENT_9C2
	const EVENT_9C3
	const EVENT_9C4
	const EVENT_9C5
	const EVENT_9C6
	const EVENT_9C7
	const EVENT_9C8
	const EVENT_9C9
	const EVENT_9CA
	const EVENT_9CB
	const EVENT_9CC
	const EVENT_9CD
	const EVENT_9CE
	const EVENT_9CF
	const EVENT_9D0
	const EVENT_9D1
	const EVENT_9D2
	const EVENT_9D3
	const EVENT_9D4
	const EVENT_9D5
	const EVENT_9D6
	const EVENT_9D7
	const EVENT_9D8
	const EVENT_9D9
	const EVENT_9DA
	const EVENT_9DB
	const EVENT_9DC
	const EVENT_9DD
	const EVENT_9DE
	const EVENT_9DF
	const EVENT_9E0
	const EVENT_9E1
	const EVENT_9E2
	const EVENT_9E3
	const EVENT_9E4
	const EVENT_9E5
	const EVENT_9E6
	const EVENT_9E7
	const EVENT_9E8
	const EVENT_9E9
	const EVENT_9EA
	const EVENT_9EB
	const EVENT_9EC
	const EVENT_9ED
	const EVENT_9EE
	const EVENT_9EF
	const EVENT_9F0
	const EVENT_9F1
	const EVENT_9F2
	const EVENT_9F3
	const EVENT_9F4
	const EVENT_9F5
	const EVENT_9F6
	const EVENT_9F7
	const EVENT_9F8
	const EVENT_9F9
	const EVENT_9FA
	const EVENT_9FB
	const EVENT_9FC
	const EVENT_9FD
	const EVENT_9FE
	const EVENT_9FF
	const EVENT_A00
	const EVENT_A01
	const EVENT_A02
	const EVENT_A03
	const EVENT_A04
	const EVENT_A05
	const EVENT_A06
	const EVENT_A07
	const EVENT_A08
	const EVENT_A09
	const EVENT_A0A
	const EVENT_A0B
	const EVENT_A0C
	const EVENT_A0D
	const EVENT_A0E
	const EVENT_A0F
	const EVENT_A10
	const EVENT_A11
	const EVENT_A12
	const EVENT_A13
	const EVENT_A14
	const EVENT_A15
	const EVENT_A16
	const EVENT_A17
	const EVENT_A18
	const EVENT_A19
	const EVENT_A1A
	const EVENT_A1B
	const EVENT_A1C
	const EVENT_A1D
	const EVENT_A1E
	const EVENT_A1F
	const EVENT_A20
	const EVENT_A21
	const EVENT_A22
	const EVENT_A23
	const EVENT_A24
	const EVENT_A25
	const EVENT_A26
	const EVENT_A27
	const EVENT_A28
	const EVENT_A29
	const EVENT_A2A
	const EVENT_A2B
	const EVENT_A2C
	const EVENT_A2D
	const EVENT_A2E
	const EVENT_A2F
	const EVENT_A30
	const EVENT_A31
	const EVENT_A32
	const EVENT_A33
	const EVENT_A34
	const EVENT_A35
	const EVENT_A36
	const EVENT_A37
	const EVENT_A38
	const EVENT_A39
	const EVENT_A3A
	const EVENT_A3B
	const EVENT_A3C
	const EVENT_A3D
	const EVENT_A3E
	const EVENT_A3F
	const EVENT_A40
	const EVENT_A41
	const EVENT_A42
	const EVENT_A43
	const EVENT_A44
	const EVENT_A45
	const EVENT_A46
	const EVENT_A47
	const EVENT_A48
	const EVENT_A49
	const EVENT_A4A
	const EVENT_A4B
	const EVENT_A4C
	const EVENT_A4D
	const EVENT_A4E
	const EVENT_A4F
	const EVENT_A50
	const EVENT_A51
	const EVENT_A52
	const EVENT_A53
	const EVENT_A54
	const EVENT_A55
	const EVENT_A56
	const EVENT_A57
	const EVENT_A58
	const EVENT_A59
	const EVENT_A5A
	const EVENT_A5B
	const EVENT_A5C
	const EVENT_A5D
	const EVENT_A5E
	const EVENT_A5F
	const EVENT_A60
	const EVENT_A61
	const EVENT_A62
	const EVENT_A63
	const EVENT_A64
	const EVENT_A65
	const EVENT_A66
	const EVENT_A67
	const EVENT_A68
	const EVENT_A69
	const EVENT_A6A
	const EVENT_A6B
	const EVENT_A6C
	const EVENT_A6D
	const EVENT_A6E
	const EVENT_A6F
	const EVENT_A70
	const EVENT_A71
	const EVENT_A72
	const EVENT_A73
	const EVENT_A74
	const EVENT_A75
	const EVENT_A76
	const EVENT_A77
	const EVENT_A78
	const EVENT_A79
	const EVENT_A7A
	const EVENT_A7B
	const EVENT_A7C
	const EVENT_A7D
	const EVENT_A7E
	const EVENT_A7F
	const EVENT_A80
	const EVENT_A81
	const EVENT_A82
	const EVENT_A83
	const EVENT_A84
	const EVENT_A85
	const EVENT_A86
	const EVENT_A87
	const EVENT_A88
	const EVENT_A89
	const EVENT_A8A
	const EVENT_A8B
	const EVENT_A8C
	const EVENT_A8D
	const EVENT_A8E
	const EVENT_A8F
	const EVENT_A90
	const EVENT_A91
	const EVENT_A92
	const EVENT_A93
	const EVENT_A94
	const EVENT_A95
	const EVENT_A96
	const EVENT_A97
	const EVENT_A98
	const EVENT_A99
	const EVENT_A9A
	const EVENT_A9B
	const EVENT_A9C
	const EVENT_A9D
	const EVENT_A9E
	const EVENT_A9F
	const EVENT_AA0
	const EVENT_AA1
	const EVENT_AA2
	const EVENT_AA3
	const EVENT_AA4
	const EVENT_AA5
	const EVENT_AA6
	const EVENT_AA7
	const EVENT_AA8
	const EVENT_AA9
	const EVENT_AAA
	const EVENT_AAB
	const EVENT_AAC
	const EVENT_AAD
	const EVENT_AAE
	const EVENT_AAF
	const EVENT_AB0
	const EVENT_AB1
	const EVENT_AB2
	const EVENT_AB3
	const EVENT_AB4
	const EVENT_AB5
	const EVENT_AB6
	const EVENT_AB7
	const EVENT_AB8
	const EVENT_AB9
	const EVENT_ABA
	const EVENT_ABB
	const EVENT_ABC
	const EVENT_ABD
	const EVENT_ABE
	const EVENT_ABF
	const EVENT_AC0
	const EVENT_AC1
	const EVENT_AC2
	const EVENT_AC3
	const EVENT_AC4
	const EVENT_AC5
	const EVENT_AC6
	const EVENT_AC7
	const EVENT_AC8
	const EVENT_AC9
	const EVENT_ACA
	const EVENT_ACB
	const EVENT_ACC
	const EVENT_ACD
	const EVENT_ACE
	const EVENT_ACF
	const EVENT_AD0
	const EVENT_AD1
	const EVENT_AD2
	const EVENT_AD3
	const EVENT_AD4
	const EVENT_AD5
	const EVENT_AD6
	const EVENT_AD7
	const EVENT_AD8
	const EVENT_AD9
	const EVENT_ADA
	const EVENT_ADB
	const EVENT_ADC
	const EVENT_ADD
	const EVENT_ADE
	const EVENT_ADF
	const EVENT_AE0
	const EVENT_AE1
	const EVENT_AE2
	const EVENT_AE3
	const EVENT_AE4
	const EVENT_AE5
	const EVENT_AE6
	const EVENT_AE7
	const EVENT_AE8
	const EVENT_AE9
	const EVENT_AEA
	const EVENT_AEB
	const EVENT_AEC
	const EVENT_AED
	const EVENT_AEE
	const EVENT_AEF
	const EVENT_AF0
	const EVENT_AF1
	const EVENT_AF2
	const EVENT_AF3
	const EVENT_AF4
	const EVENT_AF5
	const EVENT_AF6
	const EVENT_AF7
	const EVENT_AF8
	const EVENT_AF9
	const EVENT_AFA
	const EVENT_AFB
	const EVENT_AFC
	const EVENT_AFD
	const EVENT_AFE
	const EVENT_AFF
	const EVENT_B00
	const EVENT_B01
	const EVENT_B02
	const EVENT_B03
	const EVENT_B04
	const EVENT_B05
	const EVENT_B06
	const EVENT_B07
	const EVENT_B08
	const EVENT_B09
	const EVENT_B0A
	const EVENT_B0B
	const EVENT_B0C
	const EVENT_B0D
	const EVENT_B0E
	const EVENT_B0F
	const EVENT_B10
	const EVENT_B11
	const EVENT_B12
	const EVENT_B13
	const EVENT_B14
	const EVENT_B15
	const EVENT_B16
	const EVENT_B17
	const EVENT_B18
	const EVENT_B19
	const EVENT_B1A
	const EVENT_B1B
	const EVENT_B1C
	const EVENT_B1D
	const EVENT_B1E
	const EVENT_B1F
	const EVENT_B20
	const EVENT_B21
	const EVENT_B22
	const EVENT_B23
	const EVENT_B24
	const EVENT_B25
	const EVENT_B26
	const EVENT_B27
	const EVENT_B28
	const EVENT_B29
	const EVENT_B2A
	const EVENT_B2B
	const EVENT_B2C
	const EVENT_B2D
	const EVENT_B2E
	const EVENT_B2F
	const EVENT_B30
	const EVENT_B31
	const EVENT_B32
	const EVENT_B33
	const EVENT_B34
	const EVENT_B35
	const EVENT_B36
	const EVENT_B37
	const EVENT_B38
	const EVENT_B39
	const EVENT_B3A
	const EVENT_B3B
	const EVENT_B3C
	const EVENT_B3D
	const EVENT_B3E
	const EVENT_B3F
	const EVENT_B40
	const EVENT_B41
	const EVENT_B42
	const EVENT_B43
	const EVENT_B44
	const EVENT_B45
	const EVENT_B46
	const EVENT_B47
	const EVENT_B48
	const EVENT_B49
	const EVENT_B4A
	const EVENT_B4B
	const EVENT_B4C
	const EVENT_B4D
	const EVENT_B4E
	const EVENT_B4F
	const EVENT_B50
	const EVENT_B51
	const EVENT_B52
	const EVENT_B53
	const EVENT_B54
	const EVENT_B55
	const EVENT_B56
	const EVENT_B57
	const EVENT_B58
	const EVENT_B59
	const EVENT_B5A
	const EVENT_B5B
	const EVENT_B5C
	const EVENT_B5D
	const EVENT_B5E
	const EVENT_B5F
	const EVENT_B60
	const EVENT_B61
	const EVENT_B62
	const EVENT_B63
	const EVENT_B64
	const EVENT_B65
	const EVENT_B66
	const EVENT_B67
	const EVENT_B68
	const EVENT_B69
	const EVENT_B6A
	const EVENT_B6B
	const EVENT_B6C
	const EVENT_B6D
	const EVENT_B6E
	const EVENT_B6F
	const EVENT_B70
	const EVENT_B71
	const EVENT_B72
	const EVENT_B73
	const EVENT_B74
	const EVENT_B75
	const EVENT_B76
	const EVENT_B77
	const EVENT_B78
	const EVENT_B79
	const EVENT_B7A
	const EVENT_B7B
	const EVENT_B7C
	const EVENT_B7D
	const EVENT_B7E
	const EVENT_B7F
	const EVENT_B80
	const EVENT_B81
	const EVENT_B82
	const EVENT_B83
	const EVENT_B84
	const EVENT_B85
	const EVENT_B86
	const EVENT_B87
	const EVENT_B88
	const EVENT_B89
	const EVENT_B8A
	const EVENT_B8B
	const EVENT_B8C
	const EVENT_B8D
	const EVENT_B8E
	const EVENT_B8F
	const EVENT_B90
	const EVENT_B91
	const EVENT_B92
	const EVENT_B93
	const EVENT_B94
	const EVENT_B95
	const EVENT_B96
	const EVENT_B97
	const EVENT_B98
	const EVENT_B99
	const EVENT_B9A
	const EVENT_B9B
	const EVENT_B9C
	const EVENT_B9D
	const EVENT_B9E
	const EVENT_B9F
	const EVENT_BA0
	const EVENT_BA1
	const EVENT_BA2
	const EVENT_BA3
	const EVENT_BA4
	const EVENT_BA5
	const EVENT_BA6
	const EVENT_BA7
	const EVENT_BA8
	const EVENT_BA9
	const EVENT_BAA
	const EVENT_BAB
	const EVENT_BAC
	const EVENT_BAD
	const EVENT_BAE
	const EVENT_BAF
	const EVENT_BB0
	const EVENT_BB1
	const EVENT_BB2
	const EVENT_BB3
	const EVENT_BB4
	const EVENT_BB5
	const EVENT_BB6
	const EVENT_BB7
	const EVENT_BB8
	const EVENT_BB9
	const EVENT_BBA
	const EVENT_BBB
	const EVENT_BBC
	const EVENT_BBD
	const EVENT_BBE
	const EVENT_BBF
	const EVENT_BC0
	const EVENT_BC1
	const EVENT_BC2
	const EVENT_BC3
	const EVENT_BC4
	const EVENT_BC5
	const EVENT_BC6
	const EVENT_BC7
	const EVENT_BC8
	const EVENT_BC9
	const EVENT_BCA
	const EVENT_BCB
	const EVENT_BCC
	const EVENT_BCD
	const EVENT_BCE
	const EVENT_BCF
	const EVENT_BD0
	const EVENT_BD1
	const EVENT_BD2
	const EVENT_BD3
	const EVENT_BD4
	const EVENT_BD5
	const EVENT_BD6
	const EVENT_BD7
	const EVENT_BD8
	const EVENT_BD9
	const EVENT_BDA
	const EVENT_BDB
	const EVENT_BDC
	const EVENT_BDD
	const EVENT_BDE
	const EVENT_BDF
	const EVENT_BE0
	const EVENT_BE1
	const EVENT_BE2
	const EVENT_BE3
	const EVENT_BE4
	const EVENT_BE5
	const EVENT_BE6
	const EVENT_BE7
	const EVENT_BE8
	const EVENT_BE9
	const EVENT_BEA
	const EVENT_BEB
	const EVENT_BEC
	const EVENT_BED
	const EVENT_BEE
	const EVENT_BEF
	const EVENT_BF0
	const EVENT_BF1
	const EVENT_BF2
	const EVENT_BF3
	const EVENT_BF4
	const EVENT_BF5
	const EVENT_BF6
	const EVENT_BF7
	const EVENT_BF8
	const EVENT_BF9
	const EVENT_BFA
	const EVENT_BFB
	const EVENT_BFC
	const EVENT_BFD
	const EVENT_BFE
	const EVENT_BFF
	const EVENT_C00
	const EVENT_C01
	const EVENT_C02
	const EVENT_C03
	const EVENT_C04
	const EVENT_C05
	const EVENT_C06
	const EVENT_C07
	const EVENT_C08
	const EVENT_C09
	const EVENT_C0A
	const EVENT_C0B
	const EVENT_C0C
	const EVENT_C0D
	const EVENT_C0E
	const EVENT_C0F
	const EVENT_C10
	const EVENT_C11
	const EVENT_C12
	const EVENT_C13
	const EVENT_C14
	const EVENT_C15
	const EVENT_C16
	const EVENT_C17
	const EVENT_C18
	const EVENT_C19
	const EVENT_C1A
	const EVENT_C1B
	const EVENT_C1C
	const EVENT_C1D
	const EVENT_C1E
	const EVENT_C1F
	const EVENT_C20
	const EVENT_C21
	const EVENT_C22
	const EVENT_C23
	const EVENT_C24
	const EVENT_C25
	const EVENT_C26
	const EVENT_C27
	const EVENT_C28
	const EVENT_C29
	const EVENT_C2A
	const EVENT_C2B
	const EVENT_C2C
	const EVENT_C2D
	const EVENT_C2E
	const EVENT_C2F
	const EVENT_C30
	const EVENT_C31
	const EVENT_C32
	const EVENT_C33
	const EVENT_C34
	const EVENT_C35
	const EVENT_C36
	const EVENT_C37
	const EVENT_C38
	const EVENT_C39
	const EVENT_C3A
	const EVENT_C3B
	const EVENT_C3C
	const EVENT_C3D
	const EVENT_C3E
	const EVENT_C3F
	const EVENT_C40
	const EVENT_C41
	const EVENT_C42
	const EVENT_C43
	const EVENT_C44
	const EVENT_C45
	const EVENT_C46
	const EVENT_C47
	const EVENT_C48
	const EVENT_C49
	const EVENT_C4A
	const EVENT_C4B
	const EVENT_C4C
	const EVENT_C4D
	const EVENT_C4E
	const EVENT_C4F
	const EVENT_C50
	const EVENT_C51
	const EVENT_C52
	const EVENT_C53
	const EVENT_C54
	const EVENT_C55
	const EVENT_C56
	const EVENT_C57
	const EVENT_C58
	const EVENT_C59
	const EVENT_C5A
	const EVENT_C5B
	const EVENT_C5C
	const EVENT_C5D
	const EVENT_C5E
	const EVENT_C5F
	const EVENT_C60
	const EVENT_C61
	const EVENT_C62
	const EVENT_C63
	const EVENT_C64
	const EVENT_C65
	const EVENT_C66
	const EVENT_C67
	const EVENT_C68
	const EVENT_C69
	const EVENT_C6A
	const EVENT_C6B
	const EVENT_C6C
	const EVENT_C6D
	const EVENT_C6E
	const EVENT_C6F
	const EVENT_C70
	const EVENT_C71
	const EVENT_C72
	const EVENT_C73
	const EVENT_C74
	const EVENT_C75
	const EVENT_C76
	const EVENT_C77
	const EVENT_C78
	const EVENT_C79
	const EVENT_C7A
	const EVENT_C7B
	const EVENT_C7C
	const EVENT_C7D
	const EVENT_C7E
	const EVENT_C7F
	const EVENT_C80
	const EVENT_C81
	const EVENT_C82
	const EVENT_C83
	const EVENT_C84
	const EVENT_C85
	const EVENT_C86
	const EVENT_C87
	const EVENT_C88
	const EVENT_C89
	const EVENT_C8A
	const EVENT_C8B
	const EVENT_C8C
	const EVENT_C8D
	const EVENT_C8E
	const EVENT_C8F
	const EVENT_C90
	const EVENT_C91
	const EVENT_C92
	const EVENT_C93
	const EVENT_C94
	const EVENT_C95
	const EVENT_C96
	const EVENT_C97
	const EVENT_C98
	const EVENT_C99
	const EVENT_C9A
	const EVENT_C9B
	const EVENT_C9C
	const EVENT_C9D
	const EVENT_C9E
	const EVENT_C9F
	const EVENT_CA0
	const EVENT_CA1
	const EVENT_CA2
	const EVENT_CA3
	const EVENT_CA4
	const EVENT_CA5
	const EVENT_CA6
	const EVENT_CA7
	const EVENT_CA8
	const EVENT_CA9
	const EVENT_CAA
	const EVENT_CAB
	const EVENT_CAC
	const EVENT_CAD
	const EVENT_CAE
	const EVENT_CAF
	const EVENT_CB0
	const EVENT_CB1
	const EVENT_CB2
	const EVENT_CB3
	const EVENT_CB4
	const EVENT_CB5
	const EVENT_CB6
	const EVENT_CB7
	const EVENT_CB8
	const EVENT_CB9
	const EVENT_CBA
	const EVENT_CBB
	const EVENT_CBC
	const EVENT_CBD
	const EVENT_CBE
	const EVENT_CBF
	const EVENT_CC0
	const EVENT_CC1
	const EVENT_CC2
	const EVENT_CC3
	const EVENT_CC4
	const EVENT_CC5
	const EVENT_CC6
	const EVENT_CC7
	const EVENT_CC8
	const EVENT_CC9
	const EVENT_CCA
	const EVENT_CCB
	const EVENT_CCC
	const EVENT_CCD
	const EVENT_CCE
	const EVENT_CCF
	const EVENT_CD0
	const EVENT_CD1
	const EVENT_CD2
	const EVENT_CD3
	const EVENT_CD4
	const EVENT_CD5
	const EVENT_CD6
	const EVENT_CD7
	const EVENT_CD8
	const EVENT_CD9
	const EVENT_CDA
	const EVENT_CDB
	const EVENT_CDC
	const EVENT_CDD
	const EVENT_CDE
	const EVENT_CDF
	const EVENT_CE0
	const EVENT_CE1
	const EVENT_CE2
	const EVENT_CE3
	const EVENT_CE4
	const EVENT_CE5
	const EVENT_CE6
	const EVENT_CE7
	const EVENT_CE8
	const EVENT_CE9
	const EVENT_CEA
	const EVENT_CEB
	const EVENT_CEC
	const EVENT_CED
	const EVENT_CEE
	const EVENT_CEF
	const EVENT_CF0
	const EVENT_CF1
	const EVENT_CF2
	const EVENT_CF3
	const EVENT_CF4
	const EVENT_CF5
	const EVENT_CF6
	const EVENT_CF7
	const EVENT_CF8
	const EVENT_CF9
	const EVENT_CFA
	const EVENT_CFB
	const EVENT_CFC
	const EVENT_CFD
	const EVENT_CFE
	const EVENT_CFF
	const EVENT_D00
	const EVENT_D01
	const EVENT_D02
	const EVENT_D03
	const EVENT_D04
	const EVENT_D05
	const EVENT_D06
	const EVENT_D07
	const EVENT_D08
	const EVENT_D09
	const EVENT_D0A
	const EVENT_D0B
	const EVENT_D0C
	const EVENT_D0D
	const EVENT_D0E
	const EVENT_D0F
	const EVENT_D10
	const EVENT_D11
	const EVENT_D12
	const EVENT_D13
	const EVENT_D14
	const EVENT_D15
	const EVENT_D16
	const EVENT_D17
	const EVENT_D18
	const EVENT_D19
	const EVENT_D1A
	const EVENT_D1B
	const EVENT_D1C
	const EVENT_D1D
	const EVENT_D1E
	const EVENT_D1F
	const EVENT_D20
	const EVENT_D21
	const EVENT_D22
	const EVENT_D23
	const EVENT_D24
	const EVENT_D25
	const EVENT_D26
	const EVENT_D27
	const EVENT_D28
	const EVENT_D29
	const EVENT_D2A
	const EVENT_D2B
	const EVENT_D2C
	const EVENT_D2D
	const EVENT_D2E
	const EVENT_D2F
	const EVENT_D30
	const EVENT_D31
	const EVENT_D32
	const EVENT_D33
	const EVENT_D34
	const EVENT_D35
	const EVENT_D36
	const EVENT_D37
	const EVENT_D38
	const EVENT_D39
	const EVENT_D3A
	const EVENT_D3B
	const EVENT_D3C
	const EVENT_D3D
	const EVENT_D3E
	const EVENT_D3F
	const EVENT_D40
	const EVENT_D41
	const EVENT_D42
	const EVENT_D43
	const EVENT_D44
	const EVENT_D45
	const EVENT_D46
	const EVENT_D47
	const EVENT_D48
	const EVENT_D49
	const EVENT_D4A
	const EVENT_D4B
	const EVENT_D4C
	const EVENT_D4D
	const EVENT_D4E
	const EVENT_D4F
	const EVENT_D50
	const EVENT_D51
	const EVENT_D52
	const EVENT_D53
	const EVENT_D54
	const EVENT_D55
	const EVENT_D56
	const EVENT_D57
	const EVENT_D58
	const EVENT_D59
	const EVENT_D5A
	const EVENT_D5B
	const EVENT_D5C
	const EVENT_D5D
	const EVENT_D5E
	const EVENT_D5F
	const EVENT_D60
	const EVENT_D61
	const EVENT_D62
	const EVENT_D63
	const EVENT_D64
	const EVENT_D65
	const EVENT_D66
	const EVENT_D67
	const EVENT_D68
	const EVENT_D69
	const EVENT_D6A
	const EVENT_D6B
	const EVENT_D6C
	const EVENT_D6D
	const EVENT_D6E
	const EVENT_D6F
	const EVENT_D70
	const EVENT_D71
	const EVENT_D72
	const EVENT_D73
	const EVENT_D74
	const EVENT_D75
	const EVENT_D76
	const EVENT_D77
	const EVENT_D78
	const EVENT_D79
	const EVENT_D7A
	const EVENT_D7B
	const EVENT_D7C
	const EVENT_D7D
	const EVENT_D7E
	const EVENT_D7F
	const EVENT_D80
	const EVENT_D81
	const EVENT_D82
	const EVENT_D83
	const EVENT_D84
	const EVENT_D85
	const EVENT_D86
	const EVENT_D87
	const EVENT_D88
	const EVENT_D89
	const EVENT_D8A
	const EVENT_D8B
	const EVENT_D8C
	const EVENT_D8D
	const EVENT_D8E
	const EVENT_D8F
	const EVENT_D90
	const EVENT_D91
	const EVENT_D92
	const EVENT_D93
	const EVENT_D94
	const EVENT_D95
	const EVENT_D96
	const EVENT_D97
	const EVENT_D98
	const EVENT_D99
	const EVENT_D9A
	const EVENT_D9B
	const EVENT_D9C
	const EVENT_D9D
	const EVENT_D9E
	const EVENT_D9F
	const EVENT_DA0
	const EVENT_DA1
	const EVENT_DA2
	const EVENT_DA3
	const EVENT_DA4
	const EVENT_DA5
	const EVENT_DA6
	const EVENT_DA7
	const EVENT_DA8
	const EVENT_DA9
	const EVENT_DAA
	const EVENT_DAB
	const EVENT_DAC
	const EVENT_DAD
	const EVENT_DAE
	const EVENT_DAF
	const EVENT_DB0
	const EVENT_DB1
	const EVENT_DB2
	const EVENT_DB3
	const EVENT_DB4
	const EVENT_DB5
	const EVENT_DB6
	const EVENT_DB7
	const EVENT_DB8
	const EVENT_DB9
	const EVENT_DBA
	const EVENT_DBB
	const EVENT_DBC
	const EVENT_DBD
	const EVENT_DBE
	const EVENT_DBF
	const EVENT_DC0
	const EVENT_DC1
	const EVENT_DC2
	const EVENT_DC3
	const EVENT_DC4
	const EVENT_DC5
	const EVENT_DC6
	const EVENT_DC7
	const EVENT_DC8
	const EVENT_DC9
	const EVENT_DCA
	const EVENT_DCB
	const EVENT_DCC
	const EVENT_DCD
	const EVENT_DCE
	const EVENT_DCF
	const EVENT_DD0
	const EVENT_DD1
	const EVENT_DD2
	const EVENT_DD3
	const EVENT_DD4
	const EVENT_DD5
	const EVENT_DD6
	const EVENT_DD7
	const EVENT_DD8
	const EVENT_DD9
	const EVENT_DDA
	const EVENT_DDB
	const EVENT_DDC
	const EVENT_DDD
	const EVENT_DDE
	const EVENT_DDF
	const EVENT_DE0
	const EVENT_DE1
	const EVENT_DE2
	const EVENT_DE3
	const EVENT_DE4
	const EVENT_DE5
	const EVENT_DE6
	const EVENT_DE7
	const EVENT_DE8
	const EVENT_DE9
	const EVENT_DEA
	const EVENT_DEB
	const EVENT_DEC
	const EVENT_DED
	const EVENT_DEE
	const EVENT_DEF
	const EVENT_DF0
	const EVENT_DF1
	const EVENT_DF2
	const EVENT_DF3
	const EVENT_DF4
	const EVENT_DF5
	const EVENT_DF6
	const EVENT_DF7
	const EVENT_DF8
	const EVENT_DF9
	const EVENT_DFA
	const EVENT_DFB
	const EVENT_DFC
	const EVENT_DFD
	const EVENT_DFE
	const EVENT_DFF

; SEEN FLAGS
DENJUU_DEX_SEEN_FLAGS EQU const_value
	const EVENT_SEEN_TSUNONASU
	const EVENT_SEEN_KOCHIA
	const EVENT_SEEN_OSHE
	const EVENT_SEEN_KESHI
	const EVENT_SEEN_CRYPTO
	const EVENT_SEEN_MONSTERA
	const EVENT_SEEN_FUNGUS
	const EVENT_SEEN_HIOUGI
	const EVENT_SEEN_PUNICA
	const EVENT_SEEN_GUMI
	const EVENT_SEEN_SUGURI
	const EVENT_SEEN_GANRAIKOU
	const EVENT_SEEN_BYAKUBU
	const EVENT_SEEN_TELOPEA
	const EVENT_SEEN_MANTEA
	const EVENT_SEEN_IXORA
	const EVENT_SEEN_MYRTUS
	const EVENT_SEEN_LYCHNIS
	const EVENT_SEEN_LAPEIROUSIA
	const EVENT_SEEN_BUBARIA
	const EVENT_SEEN_ANGIOS
	const EVENT_SEEN_GYMNOS
	const EVENT_SEEN_LIRIOPE
	const EVENT_SEEN_WARATAH
	const EVENT_SEEN_SORGHUM
	const EVENT_SEEN_ERYNGO
	const EVENT_SEEN_NORIUTSUGI
	const EVENT_SEEN_PAMPAS
	const EVENT_SEEN_RHODANTHE
	const EVENT_SEEN_LICORICE
	const EVENT_SEEN_VIBURNUM
	const EVENT_SEEN_FUNNEL
	const EVENT_SEEN_VANDA
	const EVENT_SEEN_UIKYOU
	const EVENT_SEEN_OBANA
	const EVENT_SEEN_FIREKOKKO
	const EVENT_SEEN_RAYGOTEN
	const EVENT_SEEN_DRILARMOR
	const EVENT_SEEN_CHAMELAN
	const EVENT_SEEN_CRYPTOARM
	const EVENT_SEEN_SHELLSTERA
	const EVENT_SEEN_FUNGEIST
	const EVENT_SEEN_BALLTAMUS
	const EVENT_SEEN_BURENICA
	const EVENT_SEEN_GERON
	const EVENT_SEEN_BERZELIA
	const EVENT_SEEN_NIGELLA
	const EVENT_SEEN_MUSA
	const EVENT_SEEN_NETARO
	const EVENT_SEEN_NEJIRO
	const EVENT_SEEN_GODETIA
	const EVENT_SEEN_CURCUMA
	const EVENT_SEEN_TESSEN
	const EVENT_SEEN_HELIOPSIS
	const EVENT_SEEN_HAGUMANOKI
	const EVENT_SEEN_GILERTH
	const EVENT_SEEN_RAYGIRTH
	const EVENT_SEEN_ARMARU
	const EVENT_SEEN_CHAMERAID
	const EVENT_SEEN_CRYPTORIDE
	const EVENT_SEEN_WORMITERALA
	const EVENT_SEEN_FUNGBLADE
	const EVENT_SEEN_BULLTAMUS
	const EVENT_SEEN_PUNEEDLE
	const EVENT_SEEN_KERORIN
	const EVENT_SEEN_SUGULAI
	const EVENT_SEEN_CORTOS
	const EVENT_SEEN_GAIURUS
	const EVENT_SEEN_MIDOTOR
	const EVENT_SEEN_OCTOR
	const EVENT_SEEN_HITODEIGHT
	const EVENT_SEEN_GHOSBOAR
	const EVENT_SEEN_RASENMAI
	const EVENT_SEEN_SCORPIL
	const EVENT_SEEN_ARMCRAB
	const EVENT_SEEN_ANGIORN
	const EVENT_SEEN_GYMRACE
	const EVENT_SEEN_LIRIONPU
	const EVENT_SEEN_WHITAH
	const EVENT_SEEN_POTZAL
	const EVENT_SEEN_ARANEIDA
	const EVENT_SEEN_GADHORO
	const EVENT_SEEN_CLIOGERA
	const EVENT_SEEN_GUST
	const EVENT_SEEN_REIGE
	const EVENT_SEEN_TOGERUKA
	const EVENT_SEEN_RAIGALEON
	const EVENT_SEEN_GADORKUMA
	const EVENT_SEEN_ABIRAS
	const EVENT_SEEN_ALPHAGOS
	const EVENT_SEEN_KIYORUKA
	const EVENT_SEEN_GYMGARTH
	const EVENT_SEEN_BAIONPU
	const EVENT_SEEN_WARUTAH
	const EVENT_SEEN_GUNTZATL
	const EVENT_SEEN_ARAKUIDA
	const EVENT_SEEN_BADHORO
	const EVENT_SEEN_LAMPGERA
	const EVENT_SEEN_TEMPEST
	const EVENT_SEEN_ZUDOON
	const EVENT_SEEN_HIYU
	const EVENT_SEEN_GAMAZUMI
	const EVENT_SEEN_PAPAVER
	const EVENT_SEEN_GAMURU
	const EVENT_SEEN_BOUVARDI
	const EVENT_SEEN_GAULTHERIA
	const EVENT_SEEN_DIPSACUS
	const EVENT_SEEN_KAYA
	const EVENT_SEEN_DENFARE
	const EVENT_SEEN_ANGIEON
	const EVENT_SEEN_EASYDOG
	const EVENT_SEEN_TRICERARMOR
	const EVENT_SEEN_CRYPTOSNIPE
	const EVENT_SEEN_FUNGBOOST
	const EVENT_SEEN_VEENICA
	const EVENT_SEEN_SAIGULIGER
	const EVENT_SEEN_ARMEDURUS
	const EVENT_SEEN_OCTORIFLE
	const EVENT_SEEN_ERASERBOAR
	const EVENT_SEEN_SPEARNEEDLE
	const EVENT_SEEN_GILGIERTH
	const EVENT_SEEN_UNIARMOR
	const EVENT_SEEN_CRYPTOBURN
	const EVENT_SEEN_FUNGMACHINE
	const EVENT_SEEN_PUNISTO
	const EVENT_SEEN_SUGULINE
	const EVENT_SEEN_MACHURUS
	const EVENT_SEEN_OCTAGUN
	const EVENT_SEEN_MUMMYBOAR
	const EVENT_SEEN_KINGPIN
	const EVENT_SEEN_BEEBALM
	const EVENT_SEEN_SALAL
	const EVENT_SEEN_ENISHIDA
	const EVENT_SEEN_TULBAGHIA
	const EVENT_SEEN_KIRINGIKU
	const EVENT_SEEN_ANGILANCE
	const EVENT_SEEN_GYMGANON
	const EVENT_SEEN_SAIOPE
	const EVENT_SEEN_WATTAH
	const EVENT_SEEN_QUETZAKING
	const EVENT_SEEN_ARAKUDABARAN
	const EVENT_SEEN_PUNKHORO
	const EVENT_SEEN_VIKINGURIN
	const EVENT_SEEN_STORM
	const EVENT_SEEN_MUTOOM
	const EVENT_SEEN_GYPSOPHI
	const EVENT_SEEN_RUSCUS
	const EVENT_SEEN_MAORAN
	const EVENT_SEEN_ZEA
	const EVENT_SEEN_GONUM
	const EVENT_SEEN_ANGIPOWER
	const EVENT_SEEN_GYMZYRUS
	const EVENT_SEEN_CANONOPE
	const EVENT_SEEN_CALM
	const EVENT_SEEN_RYUUGUU
	const EVENT_SEEN_GIGAGIGERTH
	const EVENT_SEEN_BARRIARM
	const EVENT_SEEN_CRYPTOKNIGHT
	const EVENT_SEEN_FUNGWAR
	const EVENT_SEEN_BASHOU
	const EVENT_SEEN_ANGIGORGO
	const EVENT_SEEN_GYMBARON
	const EVENT_SEEN_LIRIMONARCH
	const EVENT_SEEN_ENTEIOH
	const EVENT_SEEN_GOLAKING
	const EVENT_SEEN_KANZOU
	const EVENT_SEEN_ORNITHOGALUM
	const EVENT_SEEN_GENTIANA
	const EVENT_SEEN_YARROW
	const EVENT_SEEN_ANGIOROS
	const EVENT_SEEN_GYMZATAN
	const EVENT_SEEN_DOOMSDAY
	const EVENT_SEEN_DENDEL
	const EVENT_SEEN_TELETEL
	const EVENT_EAE
	const EVENT_EAF
	const EVENT_EB0
	const EVENT_EB1
	const EVENT_EB2
	const EVENT_EB3
	const EVENT_EB4
	const EVENT_EB5
	const EVENT_EB6
	const EVENT_EB7
	const EVENT_EB8
	const EVENT_EB9
	const EVENT_EBA
	const EVENT_EBB
	const EVENT_EBC
	const EVENT_EBD
	const EVENT_EBE
	const EVENT_EBF
	const EVENT_EC0
	const EVENT_EC1
	const EVENT_EC2
	const EVENT_EC3
	const EVENT_EC4
	const EVENT_EC5
	const EVENT_EC6
	const EVENT_EC7
	const EVENT_EC8
	const EVENT_EC9
	const EVENT_ECA
	const EVENT_ECB
	const EVENT_ECC
	const EVENT_ECD
	const EVENT_ECE
	const EVENT_ECF
	const EVENT_ED0
	const EVENT_ED1
	const EVENT_ED2
	const EVENT_ED3
	const EVENT_ED4
	const EVENT_ED5
	const EVENT_ED6
	const EVENT_ED7
	const EVENT_ED8
	const EVENT_ED9
	const EVENT_EDA
	const EVENT_EDB
	const EVENT_EDC
	const EVENT_EDD
	const EVENT_EDE
	const EVENT_EDF
	const EVENT_EE0
	const EVENT_EE1
	const EVENT_EE2
	const EVENT_EE3
	const EVENT_EE4
	const EVENT_EE5
	const EVENT_EE6
	const EVENT_EE7
	const EVENT_EE8
	const EVENT_EE9
	const EVENT_EEA
	const EVENT_EEB
	const EVENT_EEC
	const EVENT_EED
	const EVENT_EEE
	const EVENT_EEF
	const EVENT_EF0
	const EVENT_EF1
	const EVENT_EF2
	const EVENT_EF3
	const EVENT_EF4
	const EVENT_EF5
	const EVENT_EF6
	const EVENT_EF7
	const EVENT_EF8
	const EVENT_EF9
	const EVENT_EFA
	const EVENT_EFB
	const EVENT_EFC
	const EVENT_EFD
	const EVENT_EFE
	const EVENT_EFF

; CAUGHT FLAGS
DENJUU_DEX_CAUGHT_FLAGS EQU const_value
	const EVENT_CAUGHT_TSUNONASU
	const EVENT_CAUGHT_KOCHIA
	const EVENT_CAUGHT_OSHE
	const EVENT_CAUGHT_KESHI
	const EVENT_CAUGHT_CRYPTO
	const EVENT_CAUGHT_MONSTERA
	const EVENT_CAUGHT_FUNGUS
	const EVENT_CAUGHT_HIOUGI
	const EVENT_CAUGHT_PUNICA
	const EVENT_CAUGHT_GUMI
	const EVENT_CAUGHT_SUGURI
	const EVENT_CAUGHT_GANRAIKOU
	const EVENT_CAUGHT_BYAKUBU
	const EVENT_CAUGHT_TELOPEA
	const EVENT_CAUGHT_MANTEA
	const EVENT_CAUGHT_IXORA
	const EVENT_CAUGHT_MYRTUS
	const EVENT_CAUGHT_LYCHNIS
	const EVENT_CAUGHT_LAPEIROUSIA
	const EVENT_CAUGHT_BUBARIA
	const EVENT_CAUGHT_ANGIOS
	const EVENT_CAUGHT_GYMNOS
	const EVENT_CAUGHT_LIRIOPE
	const EVENT_CAUGHT_WARATAH
	const EVENT_CAUGHT_SORGHUM
	const EVENT_CAUGHT_ERYNGO
	const EVENT_CAUGHT_NORIUTSUGI
	const EVENT_CAUGHT_PAMPAS
	const EVENT_CAUGHT_RHODANTHE
	const EVENT_CAUGHT_LICORICE
	const EVENT_CAUGHT_VIBURNUM
	const EVENT_CAUGHT_FUNNEL
	const EVENT_CAUGHT_VANDA
	const EVENT_CAUGHT_UIKYOU
	const EVENT_CAUGHT_OBANA
	const EVENT_CAUGHT_FIREKOKKO
	const EVENT_CAUGHT_RAYGOTEN
	const EVENT_CAUGHT_DRILARMOR
	const EVENT_CAUGHT_CHAMELAN
	const EVENT_CAUGHT_CRYPTOARM
	const EVENT_CAUGHT_SHELLSTERA
	const EVENT_CAUGHT_FUNGEIST
	const EVENT_CAUGHT_BALLTAMUS
	const EVENT_CAUGHT_BURENICA
	const EVENT_CAUGHT_GERON
	const EVENT_CAUGHT_BERZELIA
	const EVENT_CAUGHT_NIGELLA
	const EVENT_CAUGHT_MUSA
	const EVENT_CAUGHT_NETARO
	const EVENT_CAUGHT_NEJIRO
	const EVENT_CAUGHT_GODETIA
	const EVENT_CAUGHT_CURCUMA
	const EVENT_CAUGHT_TESSEN
	const EVENT_CAUGHT_HELIOPSIS
	const EVENT_CAUGHT_HAGUMANOKI
	const EVENT_CAUGHT_GILERTH
	const EVENT_CAUGHT_RAYGIRTH
	const EVENT_CAUGHT_ARMARU
	const EVENT_CAUGHT_CHAMERAID
	const EVENT_CAUGHT_CRYPTORIDE
	const EVENT_CAUGHT_WORMITERALA
	const EVENT_CAUGHT_FUNGBLADE
	const EVENT_CAUGHT_BULLTAMUS
	const EVENT_CAUGHT_PUNEEDLE
	const EVENT_CAUGHT_KERORIN
	const EVENT_CAUGHT_SUGULAI
	const EVENT_CAUGHT_CORTOS
	const EVENT_CAUGHT_GAIURUS
	const EVENT_CAUGHT_MIDOTOR
	const EVENT_CAUGHT_OCTOR
	const EVENT_CAUGHT_HITODEIGHT
	const EVENT_CAUGHT_GHOSBOAR
	const EVENT_CAUGHT_RASENMAI
	const EVENT_CAUGHT_SCORPIL
	const EVENT_CAUGHT_ARMCRAB
	const EVENT_CAUGHT_ANGIORN
	const EVENT_CAUGHT_GYMRACE
	const EVENT_CAUGHT_LIRIONPU
	const EVENT_CAUGHT_WHITAH
	const EVENT_CAUGHT_POTZAL
	const EVENT_CAUGHT_ARANEIDA
	const EVENT_CAUGHT_GADHORO
	const EVENT_CAUGHT_CLIOGERA
	const EVENT_CAUGHT_GUST
	const EVENT_CAUGHT_REIGE
	const EVENT_CAUGHT_TOGERUKA
	const EVENT_CAUGHT_RAIGALEON
	const EVENT_CAUGHT_GADORKUMA
	const EVENT_CAUGHT_ABIRAS
	const EVENT_CAUGHT_ALPHAGOS
	const EVENT_CAUGHT_KIYORUKA
	const EVENT_CAUGHT_GYMGARTH
	const EVENT_CAUGHT_BAIONPU
	const EVENT_CAUGHT_WARUTAH
	const EVENT_CAUGHT_GUNTZATL
	const EVENT_CAUGHT_ARAKUIDA
	const EVENT_CAUGHT_BADHORO
	const EVENT_CAUGHT_LAMPGERA
	const EVENT_CAUGHT_TEMPEST
	const EVENT_CAUGHT_ZUDOON
	const EVENT_CAUGHT_HIYU
	const EVENT_CAUGHT_GAMAZUMI
	const EVENT_CAUGHT_PAPAVER
	const EVENT_CAUGHT_GAMURU
	const EVENT_CAUGHT_BOUVARDI
	const EVENT_CAUGHT_GAULTHERIA
	const EVENT_CAUGHT_DIPSACUS
	const EVENT_CAUGHT_KAYA
	const EVENT_CAUGHT_DENFARE
	const EVENT_CAUGHT_ANGIEON
	const EVENT_CAUGHT_EASYDOG
	const EVENT_CAUGHT_TRICERARMOR
	const EVENT_CAUGHT_CRYPTOSNIPE
	const EVENT_CAUGHT_FUNGBOOST
	const EVENT_CAUGHT_VEENICA
	const EVENT_CAUGHT_SAIGULIGER
	const EVENT_CAUGHT_ARMEDURUS
	const EVENT_CAUGHT_OCTORIFLE
	const EVENT_CAUGHT_ERASERBOAR
	const EVENT_CAUGHT_SPEARNEEDLE
	const EVENT_CAUGHT_GILGIERTH
	const EVENT_CAUGHT_UNIARMOR
	const EVENT_CAUGHT_CRYPTOBURN
	const EVENT_CAUGHT_FUNGMACHINE
	const EVENT_CAUGHT_PUNISTO
	const EVENT_CAUGHT_SUGULINE
	const EVENT_CAUGHT_MACHURUS
	const EVENT_CAUGHT_OCTAGUN
	const EVENT_CAUGHT_MUMMYBOAR
	const EVENT_CAUGHT_KINGPIN
	const EVENT_CAUGHT_BEEBALM
	const EVENT_CAUGHT_SALAL
	const EVENT_CAUGHT_ENISHIDA
	const EVENT_CAUGHT_TULBAGHIA
	const EVENT_CAUGHT_KIRINGIKU
	const EVENT_CAUGHT_ANGILANCE
	const EVENT_CAUGHT_GYMGANON
	const EVENT_CAUGHT_SAIOPE
	const EVENT_CAUGHT_WATTAH
	const EVENT_CAUGHT_QUETZAKING
	const EVENT_CAUGHT_ARAKUDABARAN
	const EVENT_CAUGHT_PUNKHORO
	const EVENT_CAUGHT_VIKINGURIN
	const EVENT_CAUGHT_STORM
	const EVENT_CAUGHT_MUTOOM
	const EVENT_CAUGHT_GYPSOPHI
	const EVENT_CAUGHT_RUSCUS
	const EVENT_CAUGHT_MAORAN
	const EVENT_CAUGHT_ZEA
	const EVENT_CAUGHT_GONUM
	const EVENT_CAUGHT_ANGIPOWER
	const EVENT_CAUGHT_GYMZYRUS
	const EVENT_CAUGHT_CANONOPE
	const EVENT_CAUGHT_CALM
	const EVENT_CAUGHT_RYUUGUU
	const EVENT_CAUGHT_GIGAGIGERTH
	const EVENT_CAUGHT_BARRIARM
	const EVENT_CAUGHT_CRYPTOKNIGHT
	const EVENT_CAUGHT_FUNGWAR
	const EVENT_CAUGHT_BASHOU
	const EVENT_CAUGHT_ANGIGORGO
	const EVENT_CAUGHT_GYMBARON
	const EVENT_CAUGHT_LIRIMONARCH
	const EVENT_CAUGHT_ENTEIOH
	const EVENT_CAUGHT_GOLAKING
	const EVENT_CAUGHT_KANZOU
	const EVENT_CAUGHT_ORNITHOGALUM
	const EVENT_CAUGHT_GENTIANA
	const EVENT_CAUGHT_YARROW
	const EVENT_CAUGHT_ANGIOROS
	const EVENT_CAUGHT_GYMZATAN
	const EVENT_CAUGHT_DOOMSDAY
	const EVENT_CAUGHT_DENDEL
	const EVENT_CAUGHT_TELETEL
	const EVENT_FAE
	const EVENT_FAF
	const EVENT_FB0
	const EVENT_FB1
	const EVENT_FB2
	const EVENT_FB3
	const EVENT_FB4
	const EVENT_FB5
	const EVENT_FB6
	const EVENT_FB7
	const EVENT_FB8
	const EVENT_FB9
	const EVENT_FBA
	const EVENT_FBB
	const EVENT_FBC
	const EVENT_FBD
	const EVENT_FBE
	const EVENT_FBF
	const EVENT_FC0
	const EVENT_FC1
	const EVENT_FC2
	const EVENT_FC3
	const EVENT_FC4
	const EVENT_FC5
	const EVENT_FC6
	const EVENT_FC7
	const EVENT_FC8
	const EVENT_FC9
	const EVENT_FCA
	const EVENT_FCB
	const EVENT_FCC
	const EVENT_FCD
	const EVENT_FCE
	const EVENT_FCF
	const EVENT_FD0
	const EVENT_FD1
	const EVENT_FD2
	const EVENT_FD3
	const EVENT_FD4
	const EVENT_FD5
	const EVENT_FD6
	const EVENT_FD7
	const EVENT_FD8
	const EVENT_FD9
	const EVENT_FDA
	const EVENT_FDB
	const EVENT_FDC
	const EVENT_FDD
	const EVENT_FDE
	const EVENT_FDF
	const EVENT_FE0
	const EVENT_FE1
	const EVENT_FE2
	const EVENT_FE3
	const EVENT_FE4
	const EVENT_FE5
	const EVENT_FE6
	const EVENT_FE7
	const EVENT_FE8
	const EVENT_FE9
	const EVENT_FEA
	const EVENT_FEB
	const EVENT_FEC
	const EVENT_FED
	const EVENT_FEE
	const EVENT_FEF
	const EVENT_FF0
	const EVENT_FF1
	const EVENT_FF2
	const EVENT_FF3
	const EVENT_FF4
	const EVENT_FF5
	const EVENT_FF6
	const EVENT_FF7
	const EVENT_FF8
	const EVENT_FF9
	const EVENT_FFA
	const EVENT_FFB
	const EVENT_FFC
	const EVENT_FFD
	const EVENT_FFE
	const EVENT_FFF

NUM_EVENTS EQU const_value
