	const_def

	const DUMMY_0
	const CLAW
	const RUSH
	const STRIKE
	const CAT_PUNCH
	const BISON_HAMMER
	const KICK
	const TAIL
	const HORN
	const BEAK
	const POISON_STING
	const NUMBING_STING
	const SCISSOR
	const SABRE
	const BITE
	const BODY_PRESS
	const HORN_DRILL
	const BLOODSUCK
	const SHURIKEN
	const BOWGUN
	const BISON_BEAM
	const STAG_BEAM
	const PULSE_BEAM
	const PLASMA_LASER
	const MEGA_LAUNCHER
	const MEGA_CANNON
	const MEGA_RIFLE
	const DRILL_MISSILE
	const HYPER_MISSILE
	const DRAGON_MISSILE
	const PENGUIN_MISSILE
	const MISSILE_POD
	const WAR_CANNON
	const HARPOON_MISSILE
	const HORN_LAUNCHER
	const BIRD_BAZOOKA
	const NOSE_MAGNUM
	const EAR_VULCAN
	const TUSK_VULCAN
	const MACHINE_GUN
	const FLAMETHROWER
	const MINI_FLAME
	const MEGA_FLAME
	const KAMAITACHI
	const HURRICANE
	const MINI_SNOW
	const BLIZZARD
	const EGG_BOMB
	const WHIRLPOOL
	const TSUNAMI
	const MINI_BOLT
	const MEGA_BOLT
	const EARTHQUAKE
	const MEGA_QUAKE
	const ROCK ; 36
	const MEGA_ROCK
	const SPEED_UP
	const FOCUS
	const AVOID
	const INVIGORATE
	const CHARGE_UP
	const HEAL
	const RECOVER
	const RESTORE
	const SHIELD
	const PROTECT
	const IRON_WALL
	const CAMOUFLAGE
	const ULTRASONIC
	const EM_WAVE
	const CURSE_SONG
	const LULLABY
	const GLARE
	const SLEEP_GAS
	const SMOKESCREEN
	const POISON_GAS
	const JUMP
	const FLIGHT
	const SCREAM
	const WINGBEAT
	const EM_BARRIER
	const FORCE_FIELD
	const CHILL
	const HEAT_WAVE
	const WATER_SHOT
	const ACID
	const LICK
	const TENTACLE
	const ICE_BALL
	const PARAMETER_DOWN
	const STATUS_RESET
	const IRON_CLAW
	const ASSAULT
	const MISSILE_PUNCH
	const RAZOR_PUNCH
	const HOOF
	const HIGH_KICK
	const MIDDLE_KICK
	const STAB
	const TRIPLE_ATTACK
	const TOXIC_STING
	const ELECTRIC_STING
	const CROSS_ATTACK
	const VACUUM_SLASH
	const FANG_CRUSH
	const PUNT
	const SCREW_HORN
	const DRAIN
	const DENMA_SHURIKEN
	const NEEDLE
	const QUICK_STEP
	const AIM
	const EVADE
	const BRACE
	const DUMMY_1
	const FIRST_AID
	const REPAIR
	const DUMMY_2
	const SHUTTER
	const DEFEND
	const DUMMY_3
	const CONCEAL
	const EM_PULSE
	const SHOCKWAVE
	const DUMMY_4
	const DUMMY_5
	const STARE
	const DUMMY_6
	const DUMMY_7
	const DUMMY_8
	const DUMMY_9
	const DUMMY_10
	const SNARL
	const DUST_CLOUD
	const ELECTRO_SCREEN
	const DENMA_SEAL
	const FROST_BREATH
	const PETAL_STORM
