	const_def

	const MUSIC_00
	const MUSIC_NONE
	const MUSIC_02
	const MUSIC_03
	const MUSIC_04
	const MUSIC_05
	const MUSIC_06
	const MUSIC_07
	const MUSIC_08
	const MUSIC_09
	const MUSIC_0A
	const MUSIC_0B
	const MUSIC_0C
	const MUSIC_0D
	const MUSIC_0E
	const MUSIC_0F
	const MUSIC_10
	const MUSIC_11
	const MUSIC_12
	const MUSIC_13
	const MUSIC_14
	const MUSIC_15
	const MUSIC_16
	const MUSIC_17
	const MUSIC_WON_BATTLE
	const MUSIC_LOST_BATTLE
	const MUSIC_LEVEL_UP
	const MUSIC_GAME_OVER
	const MUSIC_1C
	const MUSIC_1D
	const MUSIC_1E
    const music_1F
	const MUSIC_20
	const MUSIC_21
	const MUSIC_22
	const MUSIC_23
	const MUSIC_24
	const MUSIC_25
	const MUSIC_26
	const MUSIC_27
	const MUSIC_28
	const MUSIC_29
	const MUSIC_2A
	const MUSIC_EVOLUTION
	const MUSIC_2C
	const MUSIC_2D
	const MUSIC_2E
    const music_2F
	const MUSIC_30
	const MUSIC_31
	const MUSIC_32
	const MUSIC_33
	const MUSIC_34
	const MUSIC_35
	const MUSIC_TITLE_SCREEN
	const MUSIC_37
	const MUSIC_38
	const MUSIC_39
	const MUSIC_3A
	const MUSIC_3B
	const MUSIC_3C
	const MUSIC_3D
	const MUSIC_3E
    const music_3F
