	const_def

	const KIMI
	const TOSHIKAGU
	const MINION
	const MITSUBA
	const TORLU
	const SAYURI
	const YUKIKO
	const EXPLORER
	const BLACKBELT
	const OGAWA
	const BUUTA
	const KUNISADA
	const WANDA
	const SCIENTIST
	const LASS
	const CRAFT_PROF
	const REPOMAN
	const HOSHINO
	const LUMBERJACK
	const MOM_AND_KID
	const CAVE_GIRL
	const FANGARIAN
	const BIRD
	const MANIA
	const DIAMI_AUNT
	const BJ
	const HACKLE_TOM
	const SWIMMER
	const KARATE_MAN
	const GOGO_RACER
	const PUPPY
	const CAT
	const BABY
	const THUNDER_DAD
	const RUDDER_DAD
	const QUAKE_DAD
	const KAI
	const NERIKARA
	const KAKUZA_GUARD
	const TABASCO
	const SANAEBA
	const SAITOU_29
	const SAITOU_2A
	const SAITOU_2B
	const SAITOU_2C
	const SAITOU_2D
	const SAITOU_2E
	const SAITOU_2F
 