INCLUDE "constants/misc_constants.asm"
INCLUDE "constants/move_constants.asm"
INCLUDE "constants/denjuu_constants.asm"
INCLUDE "constants/type_constants.asm"
INCLUDE "constants/base_stats_constants.asm"
