hPushOAM EQU $ff80

hFF8A EQU $ff8a
hFF8B EQU $ff8b
hJoyLast EQU $ff8c
hJoyNew EQU $ff8d
hBGMapYPixel EQU $ff8e
hBGMapXPixel EQU $ff8f
hBGMapAddr EQU $ff90
hVBlankOccurred EQU $ff92
hIE_Backup EQU $ff93
hFF94 EQU $ff94
hFF95 EQU $ff95
hFF96 EQU $ff96
hFF97 EQU $ff97
hFF98 EQU $ff98
hFF99 EQU $ff99
hFF9A EQU $ff9a
hFF9B EQU $ff9b
hFF9C EQU $ff9c
hFF9D EQU $ff9d
hFF9E EQU $ff9e
hFF9F EQU $ff9f
hMusicID EQU $ffa0
hSFX_ID EQU $ffa1
hRingtone EQU $ffa2
hFFA3 EQU $ffa3
hMusicCommand EQU $ffa4
hFFA5 EQU $ffa5
hFFA6 EQU $ffa6
hFFA7 EQU $ffa7
hFFA8 EQU $ffa8
hPCM_ID EQU $ffa9
hFFAA EQU $ffaa
hFFAB EQU $ffab
hFFAC EQU $ffac
hFFAD EQU $ffad
hFFAE EQU $ffae
hFFAF EQU $ffaf
hFFB0 EQU $ffb0
hFFB1 EQU $ffb1
hFFB2 EQU $ffb2
hFFB3 EQU $ffb3
hFFB4 EQU $ffb4
hFFB5 EQU $ffb5
hFFB6 EQU $ffb6
hFFB7 EQU $ffb7
hFFB8 EQU $ffb8
hFFB9 EQU $ffb9
hFFBA EQU $ffba
hFFBB EQU $ffbb
hFFBC EQU $ffbc
hFFBD EQU $ffbd
hFFBE EQU $ffbe
hFFBF EQU $ffbf
hFFC0 EQU $ffc0
hFFC1 EQU $ffc1
hFFC2 EQU $ffc2
hFFC3 EQU $ffc3
hFFC4 EQU $ffc4
hFFC5 EQU $ffc5
hFFC6 EQU $ffc6
hFFC7 EQU $ffc7
hFFC8 EQU $ffc8
hFFC9 EQU $ffc9
hFFCA EQU $ffca
hFFCB EQU $ffcb
hFFCC EQU $ffcc
hFFCD EQU $ffcd
hFFCE EQU $ffce
hFFCF EQU $ffcf
hFFD0 EQU $ffd0
hFFD1 EQU $ffd1
hFFD2 EQU $ffd2
hFFD3 EQU $ffd3
hFFD4 EQU $ffd4
hFFD5 EQU $ffd5
hFFD6 EQU $ffd6
hFFD7 EQU $ffd7
hFFD8 EQU $ffd8
hFFD9 EQU $ffd9
hFFDA EQU $ffda
hFFDB EQU $ffdb
hFFDC EQU $ffdc
hFFDD EQU $ffdd
hFFDE EQU $ffde
hFFDF EQU $ffdf
hFFE0 EQU $ffe0
hFFE1 EQU $ffe1
hFFE2 EQU $ffe2
hFFE3 EQU $ffe3
hFFE4 EQU $ffe4
hFFE5 EQU $ffe5
hFFE6 EQU $ffe6
hFFE7 EQU $ffe7
hFFE8 EQU $ffe8
hFFE9 EQU $ffe9
hFFEA EQU $ffea
hFFEB EQU $ffeb
hFFEC EQU $ffec
hFFED EQU $ffed
hFFEE EQU $ffee
hFFEF EQU $ffef
hFFF0 EQU $fff0
hFFF1 EQU $fff1
hFFF2 EQU $fff2
hFFF3 EQU $fff3
hFFF4 EQU $fff4
hFFF5 EQU $fff5
hFFF6 EQU $fff6
hFFF7 EQU $fff7
hFFF8 EQU $fff8
hFFF9 EQU $fff9
hFFFA EQU $fffa
hFFFB EQU $fffb
hFFFC EQU $fffc
hFFFD EQU $fffd
hFFFE EQU $fffe
